//! Machine-readable probe/profile catalog for P0.3c.
//!
//! Every successful compiling probe appears exactly once with a deterministic
//! ID, a single enabled profile, and a pinned source anchor path.

/// One catalog row: probe ID ↔ profile ↔ API path ↔ source path.
#[derive(Clone, Copy, Debug)]
pub struct ProbeCatalogEntry {
    pub id: &'static str,
    pub profile: &'static str,
    pub api_path: &'static str,
    pub source_path: &'static str,
    pub source_lines: &'static str,
    pub kind: &'static str,
}

/// Complete catalog of successful compile probes across all profiles.
pub const PROBE_CATALOG: &[ProbeCatalogEntry] = &[
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-request-type",
        profile: "profile-stable-typed",
        api_path: "ruma::api::client::search::search_events::v3::Request",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-response-type",
        profile: "profile-stable-typed",
        api_path: "ruma::api::client::search::search_events::v3::Response",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-criteria-type",
        profile: "profile-stable-typed",
        api_path: "ruma::api::client::search::search_events::v3::Criteria",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-client-send",
        profile: "profile-stable-typed",
        api_path: "Client::send(search_events::v3::Request)",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-send",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-next-batch-field",
        profile: "profile-stable-typed",
        api_path: "search_events::v3::Request::next_batch",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-field",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-search-filter-limit-fields",
        profile: "profile-stable-typed",
        api_path: "Criteria.filter (RoomEventFilter::limit/rooms)",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-field",
    },
    ProbeCatalogEntry {
        id: "P0.3c-oauth-type",
        profile: "profile-stable-typed",
        api_path: "matrix_sdk::authentication::oauth::OAuth",
        source_path: "crates/matrix-sdk/src/authentication/oauth/mod.rs",
        source_lines: "278",
        kind: "stable-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-oauth",
        profile: "profile-stable-typed",
        api_path: "Client::oauth",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "809",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-oauth-finish-login",
        profile: "profile-stable-typed",
        api_path: "OAuth::finish_login",
        source_path: "crates/matrix-sdk/src/authentication/oauth/mod.rs",
        source_lines: "931",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-oauth-refresh-access-token",
        profile: "profile-stable-typed",
        api_path: "OAuth::refresh_access_token",
        source_path: "crates/matrix-sdk/src/authentication/oauth/mod.rs",
        source_lines: "1207",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-refresh-access-token",
        profile: "profile-stable-typed",
        api_path: "Client::refresh_access_token",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1487",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-matrix-auth-get-sso-login-url",
        profile: "profile-stable-typed",
        api_path: "MatrixAuth::get_sso_login_url",
        source_path: "crates/matrix-sdk/src/authentication/matrix/mod.rs",
        source_lines: "103",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-matrix-auth-login-with-sso-callback",
        profile: "profile-stable-typed",
        api_path: "MatrixAuth::login_with_sso_callback",
        source_path: "crates/matrix-sdk/src/authentication/matrix/mod.rs",
        source_lines: "330",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-matrix-auth-login-token",
        profile: "profile-stable-typed",
        api_path: "MatrixAuth::login_token",
        source_path: "crates/matrix-sdk/src/authentication/matrix/mod.rs",
        source_lines: "287",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-matrix-auth-login-custom",
        profile: "profile-stable-typed",
        api_path: "MatrixAuth::login_custom",
        source_path: "crates/matrix-sdk/src/authentication/matrix/mod.rs",
        source_lines: "229",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-matrix-auth-refresh-access-token",
        profile: "profile-stable-typed",
        api_path: "MatrixAuth::refresh_access_token",
        source_path: "crates/matrix-sdk/src/authentication/matrix/mod.rs",
        source_lines: "510",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-delete-devices",
        profile: "profile-stable-typed",
        api_path: "Client::delete_devices",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "2686",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-rename-device",
        profile: "profile-stable-typed",
        api_path: "Client::rename_device",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "2706",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-verification-request-accept",
        profile: "profile-stable-typed",
        api_path: "VerificationRequest::accept",
        source_path: "crates/matrix-sdk/src/encryption/verification/requests.rs",
        source_lines: "148",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-verification-request-cancel",
        profile: "profile-stable-typed",
        api_path: "VerificationRequest::cancel",
        source_path: "crates/matrix-sdk/src/encryption/verification/requests.rs",
        source_lines: "207",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-verification-request-start-sas",
        profile: "profile-stable-typed",
        api_path: "VerificationRequest::start_sas",
        source_path: "crates/matrix-sdk/src/encryption/verification/requests.rs",
        source_lines: "199",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-sas-verification-accept",
        profile: "profile-stable-typed",
        api_path: "SasVerification::accept",
        source_path: "crates/matrix-sdk/src/encryption/verification/sas.rs",
        source_lines: "32",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-sas-verification-confirm",
        profile: "profile-stable-typed",
        api_path: "SasVerification::confirm",
        source_path: "crates/matrix-sdk/src/encryption/verification/sas.rs",
        source_lines: "81",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-encryption-get-verification-request",
        profile: "profile-stable-typed",
        api_path: "Encryption::get_verification_request",
        source_path: "crates/matrix-sdk/src/encryption/mod.rs",
        source_lines: "1062",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-device-request-verification",
        profile: "profile-stable-typed",
        api_path: "Device::request_verification",
        source_path: "crates/matrix-sdk/src/encryption/identities/devices.rs",
        source_lines: "142",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-recovery-enable",
        profile: "profile-stable-typed",
        api_path: "Recovery::enable",
        source_path: "crates/matrix-sdk/src/encryption/recovery/mod.rs",
        source_lines: "235",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-recovery-recover",
        profile: "profile-stable-typed",
        api_path: "Recovery::recover",
        source_path: "crates/matrix-sdk/src/encryption/recovery/mod.rs",
        source_lines: "489",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-backups-create",
        profile: "profile-stable-typed",
        api_path: "Backups::create",
        source_path: "crates/matrix-sdk/src/encryption/backups/mod.rs",
        source_lines: "97",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-send-raw",
        profile: "profile-stable-typed",
        api_path: "Room::send_raw",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "2621",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-send-state-event-raw",
        profile: "profile-stable-typed",
        api_path: "Room::send_state_event_raw",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "3281",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-account-account-data-raw",
        profile: "profile-stable-typed",
        api_path: "Account::account_data_raw",
        source_path: "crates/matrix-sdk/src/account.rs",
        source_lines: "908",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-account-set-account-data-raw",
        profile: "profile-stable-typed",
        api_path: "Account::set_account_data_raw",
        source_path: "crates/matrix-sdk/src/account.rs",
        source_lines: "1007",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-set-unread-flag",
        profile: "profile-stable-typed",
        api_path: "Room::set_unread_flag",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "3896",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-send-single-receipt",
        profile: "profile-stable-typed",
        api_path: "Room::send_single_receipt",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "2167",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-event-with-context",
        profile: "profile-stable-typed",
        api_path: "Room::event_with_context",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "978",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-rtc-foci",
        profile: "profile-stable-typed",
        api_path: "Client::rtc_foci",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "2574",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-has-active-room-call",
        profile: "profile-stable-typed",
        api_path: "Room::has_active_room_call (via Deref)",
        source_path: "crates/matrix-sdk-base/src/room/call.rs",
        source_lines: "46",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-send-message-like",
        profile: "profile-stable-typed",
        api_path: "Room::send (MessageLikeEventContent)",
        source_path: "crates/matrix-sdk/src/room/mod.rs",
        source_lines: "2540",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-unstable-poll-start-event-content-type",
        profile: "profile-stable-typed",
        api_path: "UnstablePollStartEventContent",
        source_path: "crates/matrix-sdk/src/room/edit.rs",
        source_lines: "24",
        kind: "stable-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-timeline-poll-state-type",
        profile: "profile-stable-typed",
        api_path: "matrix_sdk_ui::timeline::PollState",
        source_path: "crates/matrix-sdk-ui/src/timeline/event_item/content/polls.rs",
        source_lines: "37",
        kind: "stable-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-edited-content-poll-start-variant",
        profile: "profile-stable-typed",
        api_path: "EditedContent::PollStart",
        source_path: "crates/matrix-sdk/src/room/edit.rs",
        source_lines: "61",
        kind: "stable-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-typed-delayed-message-event-request",
        profile: "profile-stable-typed",
        api_path: "delayed_message_event::unstable::Request via Client::send",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "1960",
        kind: "typed-request-send",
    },
    ProbeCatalogEntry {
        id: "P0.3c-search-index-type",
        profile: "profile-experimental-search",
        api_path: "matrix_sdk::search_index::SearchIndex",
        source_path: "crates/matrix-sdk/src/search_index/mod.rs",
        source_lines: "58",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-search-index-store-kind-type",
        profile: "profile-experimental-search",
        api_path: "SearchIndexStoreKind",
        source_path: "crates/matrix-sdk/src/search_index/mod.rs",
        source_lines: "47",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-search-index",
        profile: "profile-experimental-search",
        api_path: "Client::search_index",
        source_path: "crates/matrix-sdk/src/client/mod.rs",
        source_lines: "3375",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-builder-search-index-store",
        profile: "profile-experimental-search",
        api_path: "ClientBuilder::search_index_store",
        source_path: "crates/matrix-sdk/src/client/builder/mod.rs",
        source_lines: "543",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-room-search-local-index",
        profile: "profile-experimental-search",
        api_path: "Room::search (local RoomIndex)",
        source_path: "crates/matrix-sdk/src/message_search.rs",
        source_lines: "83",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-search-messages",
        profile: "profile-experimental-search",
        api_path: "Client::search_messages",
        source_path: "crates/matrix-sdk/src/message_search.rs",
        source_lines: "259",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-driver-type",
        profile: "profile-experimental-widgets",
        api_path: "WidgetDriver",
        source_path: "crates/matrix-sdk/src/widget/mod.rs",
        source_lines: "56",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-driver-handle-type",
        profile: "profile-experimental-widgets",
        api_path: "WidgetDriverHandle",
        source_path: "crates/matrix-sdk/src/widget/mod.rs",
        source_lines: "80",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-settings-type",
        profile: "profile-experimental-widgets",
        api_path: "WidgetSettings",
        source_path: "crates/matrix-sdk/src/widget/settings/mod.rs",
        source_lines: "33",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-driver-new",
        profile: "profile-experimental-widgets",
        api_path: "WidgetDriver::new",
        source_path: "crates/matrix-sdk/src/widget/mod.rs",
        source_lines: "119",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-settings-generate-webview-url",
        profile: "profile-experimental-widgets",
        api_path: "WidgetSettings::generate_webview_url",
        source_path: "crates/matrix-sdk/src/widget/settings/mod.rs",
        source_lines: "93",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-new-virtual-element-call",
        profile: "profile-experimental-widgets",
        api_path: "WidgetSettings::new_virtual_element_call_widget",
        source_path: "crates/matrix-sdk/src/widget/settings/element_call.rs",
        source_lines: "337",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-capabilities-type",
        profile: "profile-experimental-widgets",
        api_path: "Capabilities",
        source_path: "crates/matrix-sdk/src/widget/capabilities.rs",
        source_lines: "45",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-capabilities-send-read-fields",
        profile: "profile-experimental-widgets",
        api_path: "Capabilities::{send,read,send_delayed_event,...}",
        source_path: "crates/matrix-sdk/src/widget/capabilities.rs",
        source_lines: "45",
        kind: "experimental-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-widget-to-device-event-filter-type",
        profile: "profile-experimental-widgets",
        api_path: "ToDeviceEventFilter",
        source_path: "crates/matrix-sdk/src/widget/filter.rs",
        source_lines: "136",
        kind: "experimental-api-type",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-builder-sqlite-store",
        profile: "profile-sqlite",
        api_path: "ClientBuilder::sqlite_store",
        source_path: "crates/matrix-sdk/src/client/builder/mod.rs",
        source_lines: "255",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-builder-sqlite-store-with-cache-path",
        profile: "profile-sqlite",
        api_path: "ClientBuilder::sqlite_store_with_cache_path",
        source_path: "crates/matrix-sdk/src/client/builder/mod.rs",
        source_lines: "266",
        kind: "stable-api-fn",
    },
    ProbeCatalogEntry {
        id: "P0.3c-client-builder-sqlite-store-with-config",
        profile: "profile-sqlite",
        api_path: "ClientBuilder::sqlite_store_with_config_and_cache_path",
        source_path: "crates/matrix-sdk/src/client/builder/mod.rs",
        source_lines: "284",
        kind: "stable-api-fn",
    },
];

/// Flat list of all successful probe IDs (catalog order).
pub const ALL_PROBE_IDS: &[&str] = &[
    "P0.3c-typed-search-request-type",
    "P0.3c-typed-search-response-type",
    "P0.3c-typed-search-criteria-type",
    "P0.3c-typed-search-client-send",
    "P0.3c-typed-search-next-batch-field",
    "P0.3c-typed-search-filter-limit-fields",
    "P0.3c-oauth-type",
    "P0.3c-client-oauth",
    "P0.3c-oauth-finish-login",
    "P0.3c-oauth-refresh-access-token",
    "P0.3c-client-refresh-access-token",
    "P0.3c-matrix-auth-get-sso-login-url",
    "P0.3c-matrix-auth-login-with-sso-callback",
    "P0.3c-matrix-auth-login-token",
    "P0.3c-matrix-auth-login-custom",
    "P0.3c-matrix-auth-refresh-access-token",
    "P0.3c-client-delete-devices",
    "P0.3c-client-rename-device",
    "P0.3c-verification-request-accept",
    "P0.3c-verification-request-cancel",
    "P0.3c-verification-request-start-sas",
    "P0.3c-sas-verification-accept",
    "P0.3c-sas-verification-confirm",
    "P0.3c-encryption-get-verification-request",
    "P0.3c-device-request-verification",
    "P0.3c-recovery-enable",
    "P0.3c-recovery-recover",
    "P0.3c-backups-create",
    "P0.3c-room-send-raw",
    "P0.3c-room-send-state-event-raw",
    "P0.3c-account-account-data-raw",
    "P0.3c-account-set-account-data-raw",
    "P0.3c-room-set-unread-flag",
    "P0.3c-room-send-single-receipt",
    "P0.3c-room-event-with-context",
    "P0.3c-client-rtc-foci",
    "P0.3c-room-has-active-room-call",
    "P0.3c-room-send-message-like",
    "P0.3c-unstable-poll-start-event-content-type",
    "P0.3c-timeline-poll-state-type",
    "P0.3c-edited-content-poll-start-variant",
    "P0.3c-typed-delayed-message-event-request",
    "P0.3c-search-index-type",
    "P0.3c-search-index-store-kind-type",
    "P0.3c-client-search-index",
    "P0.3c-client-builder-search-index-store",
    "P0.3c-room-search-local-index",
    "P0.3c-client-search-messages",
    "P0.3c-widget-driver-type",
    "P0.3c-widget-driver-handle-type",
    "P0.3c-widget-settings-type",
    "P0.3c-widget-driver-new",
    "P0.3c-widget-settings-generate-webview-url",
    "P0.3c-widget-new-virtual-element-call",
    "P0.3c-widget-capabilities-type",
    "P0.3c-widget-capabilities-send-read-fields",
    "P0.3c-widget-to-device-event-filter-type",
    "P0.3c-client-builder-sqlite-store",
    "P0.3c-client-builder-sqlite-store-with-cache-path",
    "P0.3c-client-builder-sqlite-store-with-config",
];

/// Look up the exclusive profile for a probe ID.
pub fn profile_for_probe(id: &str) -> Option<&'static str> {
    PROBE_CATALOG.iter().find(|e| e.id == id).map(|e| e.profile)
}
