use std::path::Path;

#[path = "build_support/build_inputs.rs"]
mod build_inputs;

const DESKTOP_COMMANDS: &[&str] = &[
    "desktop_show",
    "desktop_hide",
    "desktop_window_minimize",
    "desktop_window_toggle_maximize",
    "desktop_window_close",
    "desktop_render_markdown",
    "desktop_navigate",
    "desktop_set_badge_count",
    "desktop_play_notification_sound",
    "desktop_set_shortcuts",
    "desktop_secret_store_status",
    "desktop_get_integration_status",
    "desktop_update_tray_state",
    "desktop_get_notification_permission",
    "desktop_request_notification_permission",
    "desktop_notify",
    "desktop_dismiss_notifications",
    "desktop_open_external_url",
    "desktop_save_file",
    "desktop_save_file_begin",
    "desktop_save_file_chunk",
    "desktop_save_file_end",
    "desktop_save_file_abort",
    "desktop_read_dropped_files",
    "desktop_read_dropped_file_chunk",
    "desktop_read_dropped_file_end",
    "desktop_get_performance_capabilities",
    "desktop_append_log",
    "desktop_log_path",
    "desktop_record_diagnostic",
    "desktop_diagnostics_status",
    "desktop_read_diagnostics",
    "desktop_clear_diagnostics",
    "desktop_agent_action",
    "matrix_login_flows",
    "matrix_store_recovery_prepare",
    "matrix_threepid_add_email",
    "matrix_threepid_add_email_password",
    "matrix_threepid_delete",
    "matrix_threepid_request_email_token",
    "matrix_threepid_snapshot",
    "matrix_store_recovery_confirm",
    "matrix_sync_recover",
    "matrix_password_reset_request_email_token",
    "matrix_password_reset_complete",
    "matrix_register_flows",
    "matrix_register_request_email_token",
    "matrix_register",
    "matrix_session_identity",
    "matrix_cross_signing_status",
    "matrix_cross_signing_setup",
    "matrix_cross_signing_setup_password",
    "matrix_backup_status",
    "matrix_backup_setup",
    "matrix_backup_restore",
    "matrix_backup_repair",
    "matrix_secret_storage_status",
    "matrix_secret_storage_bootstrap",
    "matrix_secret_storage_unlock",
    "matrix_secret_storage_reset",
    "matrix_room_key_transfer_status",
    "matrix_room_key_export",
    "matrix_room_key_import_select",
    "matrix_room_key_import",
    "matrix_device_snapshot",
    "matrix_device_rename",
    "matrix_device_delete_start",
    "matrix_device_delete_password",
    "matrix_device_delete_cancel",
    "matrix_x509_identity_status",
    "matrix_x509_identity_set_enabled",
    "matrix_x509_identity_import_ca",
    "matrix_x509_identity_remove_ca",
    "matrix_x509_identity_import_signer",
    "matrix_inbox_notifications",
    "matrix_invites_snapshot",
    "matrix_invites_accept",
    "matrix_invites_decline",
    "matrix_room_create",
    "matrix_room_leave",
    "matrix_room_join",
    "matrix_room_set_favorite",
    "matrix_room_set_read_state",
    "matrix_room_identity_warnings",
    "matrix_room_identity_warning_resolve",
    "matrix_room_invite",
    "matrix_room_kick",
    "matrix_room_ban",
    "matrix_room_unban",
    "matrix_room_set_power_level",
    "matrix_room_set_power_levels",
    "matrix_room_set_power_level_tags",
    "matrix_room_members_snapshot",
    "matrix_room_power_levels_snapshot",
    "matrix_room_retention",
    "matrix_room_creators_snapshot",
    "matrix_room_power_level_tags_snapshot",
    "matrix_room_directory_protocols",
    "matrix_room_directory_search",
    "matrix_room_directory_cancel",
    "matrix_invites_report_spam",
    "matrix_invites_block_sender",
    "matrix_typing_snapshot",
    "matrix_typing_set",
    "matrix_presence_set",
    "matrix_presence_snapshot",
    "matrix_presence_subscribe",
    "matrix_presence_unsubscribe",
    "matrix_rtc_transports_refresh",
    "matrix_rtc_transports_snapshot",
    "matrix_widgets_list",
    "matrix_widget_open",
    "matrix_widget_close",
    "matrix_widget_post",
    "matrix_widget_subscribe",
    "widget_bridge_post",
    "matrix_push_rules_add_keyword",
    "matrix_push_rules_remove_keyword",
    "matrix_push_rules_set_default",
    "matrix_push_rules_set_mention",
    "matrix_push_rules_snapshot",
    "matrix_agent_notification_preferences_set",
    "matrix_agent_notification_preferences_snapshot",
    "matrix_room_notification_set",
    "matrix_room_notification_snapshot",
    "matrix_room_notifications_snapshot",
    "matrix_timeline_reaction_toggle",
    "matrix_reaction_ensure",
    "matrix_agent_approval_decide",
    "matrix_agent_approval_history_snapshot",
    "matrix_agent_approvals_list",
    "matrix_reaction_redact",
    "matrix_space_parents_snapshot",
    "matrix_space_hierarchy_snapshot",
    "matrix_space_children_snapshot",
    "matrix_space_child_set",
    "matrix_space_child_remove",
    "matrix_restricted_join_reparent",
    "matrix_mdirect_snapshot",
    "matrix_mdirect_add",
    "matrix_mdirect_remove",
    "matrix_get_user_image_pack",
    "matrix_set_user_image_pack",
    "matrix_set_global_image_packs",
    "matrix_set_room_image_pack",
    "matrix_upload_media",
    "matrix_media_config",
    "matrix_media_save",
    "matrix_media_text_preview",
    "matrix_media_preview",
    "matrix_set_own_avatar",
    "matrix_set_own_display_name",
    "matrix_get_own_profile",
    "matrix_ignored_users_ignore",
    "matrix_ignored_users_snapshot",
    "matrix_ignored_users_unignore",
    "matrix_user_directory_search",
    "matrix_user_status_clear",
    "matrix_user_status_set",
    "matrix_user_status_snapshot",
    "matrix_message_search",
    "matrix_set_room_name",
    "matrix_set_room_topic",
    "matrix_set_room_avatar",
    "matrix_send_state_event",
    "matrix_enable_room_encrypted_state",
    "matrix_set_encrypted_state_events_setting",
    "matrix_get_room_directory_visibility",
    "matrix_set_room_directory_visibility",
    "matrix_room_join_rule_snapshot",
    "matrix_room_set_join_rule",
    "matrix_get_room_image_packs",
    "matrix_get_global_image_packs",
    "matrix_later_snapshot",
    "matrix_later_upsert",
    "matrix_later_complete",
    "matrix_later_snooze",
    "matrix_later_clear_completed",
    "matrix_later_mark_reminded",
    "matrix_room_notes_snapshot",
    "matrix_room_notes_upsert",
    "matrix_room_notes_delete",
    "matrix_room_notes_complete_todo",
    "matrix_room_notes_move_todo",
    "matrix_send_text",
    "matrix_local_echo_discard",
    "matrix_local_echo_retry",
    "matrix_send_attachment",
    "matrix_send_poll",
    "matrix_edit_message",
    "matrix_poll_respond",
    "matrix_timeline_set_read_state",
    "matrix_timeline_close",
    "matrix_timeline_event_readback",
    "matrix_timeline_timestamp_to_event",
    "matrix_timeline_follow_live",
    "matrix_timeline_jump_latest",
    "matrix_timeline_edit_text",
    "matrix_timeline_redact",
    "matrix_timeline_forward_text",
    "matrix_timeline_forward_media",
    "matrix_timeline_report",
    "matrix_timeline_pin",
    "matrix_timeline_unpin",
    "matrix_pinned_events",
    "matrix_timeline_poll_vote",
    "matrix_timeline_call_decline",
    "matrix_composer_set_reply_draft",
    "matrix_composer_clear_reply_draft",
    "matrix_composer_get_reply_draft",
    "matrix_thread_list",
];

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set");
    let manifest_path = Path::new(&manifest_dir);
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-changed=build_support/build_inputs.rs");
    build_inputs::sync_release_hardening_capability(manifest_path, &profile)
        .expect("sync release-hardening capability");
    if profile == "release" {
        println!(
            "cargo:rerun-if-changed={}",
            manifest_path
                .join("capabilities/release-hardening.json")
                .display()
        );
    }

    let repo = manifest_path.parent().unwrap_or(Path::new(&manifest_dir));
    let revision = build_inputs::git_output(repo, &["rev-parse", "--short=12", "HEAD"])
        .unwrap_or_else(|| "unknown".to_owned());
    let branch = build_inputs::git_output(repo, &["branch", "--show-current"])
        .unwrap_or_else(|| "unknown".to_owned());

    for path in build_inputs::git_watch_paths(repo) {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rustc-env=SYNARA_DESKTOP_BUILD_REVISION={revision}");
    println!("cargo:rustc-env=SYNARA_DESKTOP_BUILD_BRANCH={branch}");

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(DESKTOP_COMMANDS)),
    )
    .expect("failed to run Tauri build script")
}
