use super::*;
use super::{
    account_data::*, auth_commands::*, backup::*, cross_signing::*, devices::*, media::*,
    members::*, presence::*, room_keys::*, room_ops::*, room_profile::*, secret_storage::*,
    send::*, spaces::*, timeline::*, typing::*, user_profile::*, verification::*,
};
use crate::matrix::presence::{
    NativePresenceSnapshot, NativePresenceSnapshotResult, NativePresenceState,
    NativePresenceUpdate, NativePresenceUpdateOutcome,
};
use crate::matrix::room_profile::NativeRoomJoinRuleUpdate;

const PRODUCT_SOURCE: &str = concat!(
    include_str!("product_commands.rs"),
    include_str!("../account_data/product_commands.rs"),
    include_str!("../backup/product_commands.rs"),
    include_str!("../cross_signing/product_commands.rs"),
    include_str!("../devices/product_commands.rs"),
    include_str!("../media/product_commands.rs"),
    include_str!("../members/product_commands.rs"),
    include_str!("../presence/product_commands.rs"),
    include_str!("../room_list/product_commands.rs"),
    include_str!("../room_ops/product_commands.rs"),
    include_str!("../room_profile/product_commands.rs"),
    include_str!("../room_keys/product_commands.rs"),
    include_str!("../secret_storage/product_commands.rs"),
    include_str!("../send/product_commands.rs"),
    include_str!("../spaces/product_commands.rs"),
    include_str!("../timeline/product_commands.rs"),
    include_str!("../typing/product_commands.rs"),
    include_str!("../user_profile/product_commands.rs"),
    include_str!("../verification/product_commands.rs"),
    include_str!("product.rs"),
);

// Auth commands live in the extracted product_commands.rs module. Source
// guards for the password-only product boundary must inspect that owner
// directly rather than the product.rs module wrapper.
const AUTH_PRODUCT_COMMANDS_SOURCE: &str = include_str!("product_commands.rs");
const DEVICE_PRODUCT_COMMANDS_SOURCE: &str = include_str!("../devices/product_commands.rs");
const LOGIN_SOURCE: &str = include_str!("../../../../crates/synara-core/src/app/auth/login.rs");

#[test]
fn v_presence_registers_the_frozen_native_surface() {
    let presence_source = include_str!("../presence/product_commands.rs");
    let lib_source = include_str!("../../lib.rs");
    for command in [
        "matrix_presence_snapshot",
        "matrix_presence_subscribe",
        "matrix_presence_unsubscribe",
    ] {
        assert!(presence_source.contains(command));
        assert!(lib_source.contains(command));
    }
    let live_source = include_str!("../presence/live.rs");
    assert!(live_source.contains("matrix-presence-updated"));
    assert!(!live_source.contains("access_token"));
    assert!(!live_source.contains("refresh_token"));
}

#[test]
fn room_publish_join_rule_snapshot_registers_one_native_read_owner() {
    let product = PRODUCT_SOURCE;
    let live = include_str!("../room_profile/live.rs");
    let lib = include_str!("../../lib.rs");
    let build = include_str!("../../../build.rs");
    let capability = include_str!("../../../capabilities/main.json");
    let generated =
        include_str!("../../../permissions/autogenerated/matrix_room_join_rule_snapshot.toml");
    let schemas = [
        include_str!("../../../gen/schemas/desktop-schema.json"),
        include_str!("../../../gen/schemas/linux-schema.json"),
        include_str!("../../../gen/schemas/macOS-schema.json"),
    ];

    for command in ["matrix_room_join_rule_snapshot"] {
        let capability_id = command.replace('_', "-");
        assert!(product.contains(&format!("pub async fn {command}")));
        assert!(lib.contains(command));
        assert!(build.contains(&format!("\"{command}\"")));
        assert!(capability.contains(&format!("allow-{capability_id}")));
        assert!(generated.contains(&format!("allow-{capability_id}")));
        assert!(generated.contains(&format!("deny-{capability_id}")));
        for schema in schemas {
            assert!(schema.contains(command));
        }
    }
    assert!(product.contains("get_state_event_static::<RoomJoinRulesEventContent>()"));
    assert!(product.contains("session_generation"));
    assert!(!product.contains("matrix_set_room_join_rule"));
    assert!(live.contains("matrix-room-join-rule-updated"));
    assert!(live.contains("NativeRoomJoinRuleOwner"));
    assert!(!live.contains("send_state_event"));
}

#[test]
fn room_join_rule_update_is_bounded_and_privacy_safe() {
    let ready = NativeRoomJoinRuleUpdate::Ready {
        room_id: "!room:example.org".into(),
        session_generation: 7,
        join_rule: "public",
    };
    let unavailable = NativeRoomJoinRuleUpdate::Unavailable {
        room_id: "!room:example.org".into(),
        session_generation: 7,
    };
    for value in [
        serde_json::to_string(&ready).unwrap(),
        serde_json::to_string(&unavailable).unwrap(),
    ] {
        assert!(value.contains("roomId"));
        assert!(value.contains("sessionGeneration"));
        for forbidden in ["accessToken", "refreshToken", "password", "allow"] {
            assert!(!value.contains(forbidden));
        }
    }
}

#[test]
fn presence_wire_shapes_are_camel_case_and_privacy_safe() {
    let snapshot = NativePresenceSnapshot {
        user_id: "@alice:example.org".into(),
        state: NativePresenceState::Online,
        currently_active: true,
        last_active_ts: Some(1_700_000_000_000),
        status_msg: Some("coffee".into()),
    };
    let result = NativePresenceSnapshotResult::Ready {
        session_generation: 4,
        user_id: snapshot.user_id.clone(),
        snapshot,
    };
    let raw = serde_json::to_string(&result).unwrap();
    assert!(raw.contains("sessionGeneration"));
    assert!(raw.contains("currentlyActive"));
    assert!(raw.contains("lastActiveTs"));
    for forbidden in ["accessToken", "refreshToken", "password", "ciphertext"] {
        assert!(!raw.contains(forbidden));
    }

    let update = NativePresenceUpdate {
        subscription_id: "presence-4-0".into(),
        user_id: "@alice:example.org".into(),
        session_generation: 4,
        outcome: NativePresenceUpdateOutcome::Unavailable {
            diagnostic_id: "v-presence-store-read-failed",
        },
    };
    let raw_update = serde_json::to_string(&update).unwrap();
    assert!(raw_update.contains("subscriptionId"));
    assert!(raw_update.contains("sessionGeneration"));
    assert!(raw_update.contains("diagnosticId"));
}

fn room_key_selection(selection_id: u64, label: &str) -> SelectedRoomKeyImport {
    SelectedRoomKeyImport {
        selection_id,
        path: PathBuf::from(format!("/opaque/{label}")),
        file_label: label.to_owned(),
    }
}

#[test]
fn room_key_import_reservation_is_consumed_on_success_path() {
    let mut slot = Some(room_key_selection(4, "backup.keys"));
    let reserved = reserve_room_key_import_selection(&mut slot, 4, "passphrase").unwrap();
    assert_eq!(reserved.selection_id, 4);
    assert!(slot.is_none());
}

#[test]
fn failed_room_key_import_restores_same_generation_empty_slot() {
    let mut slot = None;
    let restored = restore_reserved_room_key_import(
        7,
        Some(7),
        &mut slot,
        room_key_selection(4, "backup.keys"),
    );
    assert!(restored);
    assert_eq!(slot.as_ref().unwrap().selection_id, 4);
}

#[test]
fn failed_room_key_import_never_overwrites_newer_selection() {
    let mut slot = Some(room_key_selection(5, "newer.keys"));
    let restored = restore_reserved_room_key_import(
        7,
        Some(7),
        &mut slot,
        room_key_selection(4, "older.keys"),
    );
    assert!(!restored);
    assert_eq!(slot.as_ref().unwrap().selection_id, 5);
}

#[test]
fn failed_room_key_import_is_discarded_after_generation_change_or_logout() {
    let mut replacement_generation_slot = None;
    assert!(!restore_reserved_room_key_import(
        7,
        Some(8),
        &mut replacement_generation_slot,
        room_key_selection(4, "old.keys"),
    ));
    assert!(replacement_generation_slot.is_none());

    let mut logged_out_slot = None;
    assert!(!restore_reserved_room_key_import(
        7,
        None,
        &mut logged_out_slot,
        room_key_selection(4, "logged-out.keys"),
    ));
    assert!(logged_out_slot.is_none());
}

#[test]
fn empty_passphrase_and_invalid_room_key_selection_leave_slot_untouched() {
    let mut slot = Some(room_key_selection(4, "backup.keys"));
    let empty = reserve_room_key_import_selection(&mut slot, 4, "").unwrap_err();
    assert_eq!(empty.diagnostic_id, "v-crypto.5-passphrase-empty");
    assert_eq!(slot.as_ref().unwrap().selection_id, 4);

    let invalid = reserve_room_key_import_selection(&mut slot, 99, "passphrase").unwrap_err();
    assert_eq!(invalid.diagnostic_id, "v-crypto.5-import-selection-invalid");
    assert_eq!(slot.as_ref().unwrap().selection_id, 4);
}

#[test]
fn matrix_login_flows_dto_is_privacy_safe_and_maps_domain_flows() {
    let flows = vec![
        LoginFlow::password(),
        LoginFlow::token(true),
        LoginFlow::from_matrix_parts("m.login.sso", None),
    ];
    let response = MatrixLoginFlowsResponse {
        flows: flows.into_iter().map(MatrixLoginFlowDto::from).collect(),
    };
    assert_eq!(response.flows[0].kind, "password");
    assert_eq!(response.flows[0].matrix_type, "m.login.password");
    assert_eq!(response.flows[0].get_login_token, None);
    assert_eq!(response.flows[1].kind, "token");
    assert_eq!(response.flows[1].get_login_token, Some(true));
    assert_eq!(response.flows[2].kind, "unknown");
    assert_eq!(response.flows[2].matrix_type, "m.login.sso");

    let json = serde_json::to_value(&response).expect("serialize");
    let flows_json = json.get("flows").and_then(|v| v.as_array()).expect("flows");
    assert_eq!(flows_json.len(), 3);
    assert_eq!(flows_json[0]["kind"], "password");
    assert_eq!(flows_json[0]["matrixType"], "m.login.password");
    assert!(flows_json[0].get("getLoginToken").is_none());
    assert_eq!(flows_json[1]["getLoginToken"], true);

    let raw = serde_json::to_string(&response).expect("string");
    for forbidden in [
        "accessToken",
        "access_token",
        "refreshToken",
        "refresh_token",
        "password\":",
        "secret",
    ] {
        assert!(
            !raw.contains(forbidden),
            "login flows DTO must not contain secret field {forbidden}"
        );
    }
}

#[test]
fn map_login_flows_auth_error_is_privacy_safe() {
    let err = map_login_flows_auth_error(AuthError::HomeserverUnavailable {
        diagnostic_id: "v-auth.3-login-flows-hs",
    });
    assert_eq!(err.code, "InvalidServer");
    assert_eq!(err.diagnostic_id, "v-auth.3-login-flows-hs");
    assert!(!err.message.contains("token"));
    assert!(!err.message.contains("password"));

    let unsupported = map_login_flows_auth_error(AuthError::UnsupportedCapability {
        diagnostic_id: "r0.7-login-types-json",
    });
    assert_eq!(unsupported.code, "Unsupported");

    let invalid = map_login_flows_auth_error(AuthError::InvalidInput {
        diagnostic_id: "p3.1-empty-url",
        reason: "empty",
    });
    assert_eq!(invalid.code, "InvalidRequest");
}

#[test]
fn v_auth_3_product_registers_login_flows_command() {
    let product_prod = AUTH_PRODUCT_COMMANDS_SOURCE
        .split("#[cfg(test)]")
        .next()
        .expect("product production section");
    let lib_src = include_str!("../../lib.rs");
    assert!(
        product_prod.contains("pub async fn matrix_login_flows"),
        "V-AUTH.3 login-flow discovery command must exist"
    );
    assert!(
        lib_src.contains("matrix_login_flows"),
        "matrix_login_flows must be registered in the invoke handler"
    );
    assert!(
        product_prod.contains("crate::bridge::auth_probes::login_flows"),
        "product path must delegate login-flow discovery to the Core bridge"
    );
    assert!(
        !product_prod.contains("HttpLoginFlowTransport"),
        "product path must not instantiate a login-flow transport"
    );
    assert!(
        !product_prod.contains("discover_login_flows"),
        "product path must not call login-flow discovery directly"
    );
}

#[test]
fn login_identity_and_snapshot_serialization_never_have_token_fields() {
    let identity = MatrixLoginIdentity {
        user_id: "@alice:example.org".into(),
        device_id: "DEVICE".into(),
        homeserver_url: "https://matrix.example.org".into(),
    };
    let identity_json = serde_json::to_string(&identity).unwrap();
    let snapshot_json = serde_json::to_string(&MatrixSessionSnapshot::LoggedIn {
        user_id: identity.user_id.clone(),
        device_id: identity.device_id.clone(),
        homeserver_url: identity.homeserver_url.clone(),
        session_generation: 1,
    })
    .unwrap();
    for json in [identity_json, snapshot_json] {
        assert!(!json.contains("accessToken"));
        assert!(!json.contains("access_token"));
        assert!(!json.contains("refreshToken"));
        assert!(!json.contains("refresh_token"));
        assert!(!json.contains("password"));
    }
}

#[test]
fn matrix_session_snapshot_serializes_with_the_live_wire_keys() {
    let snapshot = MatrixSessionSnapshot::LoggedIn {
        user_id: "@alice:example.org".into(),
        device_id: "DEVICE".into(),
        homeserver_url: "https://matrix.example.org".into(),
        session_generation: 7,
    };

    assert_eq!(
        serde_json::to_value(snapshot).unwrap(),
        serde_json::json!({
            "status": "logged_in",
            "user_id": "@alice:example.org",
            "device_id": "DEVICE",
            "homeserver_url": "https://matrix.example.org",
            "sessionGeneration": 7,
        })
    );
    assert_eq!(
        serde_json::to_value(MatrixSessionSnapshot::LoggedOut).unwrap(),
        serde_json::json!({ "status": "logged_out" })
    );
}

#[test]
fn v_auth_3b_product_has_no_matrix_uia_login_stage_commands() {
    // Desktop product does not retain multi-stage UIA on the login route
    // (V-AUTH.3b). Password login remains single-shot; register/reset/device
    // delete keep specialized native stage/UIAA owners. Do not invent unused
    // matrix_uia_* session IPC for a non-product login surface.
    let product_prod = AUTH_PRODUCT_COMMANDS_SOURCE
        .split("#[cfg(test)]")
        .next()
        .expect("product production section");
    let lib_src = include_str!("../../lib.rs");
    let login_src = LOGIN_SOURCE;
    let login_prod = login_src
        .split("#[cfg(test)]")
        .next()
        .expect("login production section");

    assert!(
        product_prod.contains("pub async fn matrix_login_password"),
        "password login product command must remain registered"
    );
    assert!(
        !product_prod.contains("pub async fn matrix_uia_"),
        "generic matrix_uia_* login-stage commands must not be product Tauri commands"
    );
    assert!(
        !lib_src.contains("matrix_uia_"),
        "matrix_uia_* must not be registered in the invoke handler"
    );
    // Specialized multi-stage / UIAA product paths remain.
    assert!(
        product_prod.contains("pub async fn matrix_register"),
        "register multi-stage owner must remain"
    );
    assert!(
        product_prod.contains("pub async fn matrix_password_reset_complete"),
        "password-reset owner must remain"
    );
    assert!(
        DEVICE_PRODUCT_COMMANDS_SOURCE.contains("pub async fn matrix_device_delete_password"),
        "device-delete password UIAA owner must remain"
    );
    // Login maps UIAA to fail-closed InteractiveAuthRequired — no stage loop.
    assert!(
        login_prod.contains("InteractiveAuthRequired"),
        "login must map UIAA to InteractiveAuthRequired"
    );
    assert!(
        login_prod.contains("p3.2-login-uiaa-required"),
        "login UIAA diagnostic must remain privacy-safe"
    );
    assert!(
        !login_prod.contains("UiaSession"),
        "login module must not drive the P3.4 UiaSession coordinator"
    );
}

#[test]
fn v_auth_2_product_has_no_token_login_command_or_login_token_sdk_call() {
    // Desktop product does not retain m.login.token (V-AUTH.2). Password
    // login remains the only production Tauri login command.
    //
    // Read only production sections (exclude this tests module) so the
    // negative assertions below do not match their own string literals.
    let product_prod = AUTH_PRODUCT_COMMANDS_SOURCE
        .split("#[cfg(test)]")
        .next()
        .expect("product production section");
    let login_src = LOGIN_SOURCE;
    let login_prod = login_src
        .split("#[cfg(test)]")
        .next()
        .expect("login production section");
    let lib_src = include_str!("../../lib.rs");

    assert!(
        product_prod.contains("pub async fn matrix_login_password"),
        "password login product command must remain registered"
    );
    assert!(
        !product_prod.contains("pub async fn matrix_login_token"),
        "token login must not be a product Tauri command"
    );
    assert!(
        !lib_src.contains("matrix_login_token"),
        "token login must not be registered in the invoke handler"
    );
    assert!(
        !login_prod.contains("fn login_with_token"),
        "login_with_token foundation must not remain after V-AUTH.2 non-retention"
    );
    assert!(
        !login_prod.contains(".login_token("),
        "SDK login_token must not be called from the desktop login module"
    );

    let login_fn = product_prod
        .split("pub async fn matrix_login_password")
        .nth(1)
        .and_then(|rest| rest.split("pub async fn ").next())
        .expect("matrix_login_password body");
    // Secrets may be requested (request_refresh_token) but must not be read
    // from/returned on the product DTO path or printed.
    for forbidden in [
        "access_token",
        "login_token",
        "println!",
        "log::",
        "tracing::",
    ] {
        assert!(
            !login_fn.contains(forbidden),
            "password login product path must not reference {forbidden}"
        );
    }
    assert!(
        login_fn.contains("request_refresh_token: true"),
        "password login should request refresh tokens host-side without exposing them"
    );
    assert!(
        login_fn.contains("MatrixLoginIdentity"),
        "password login must return only privacy-safe identity fields"
    );
}

#[test]
fn crypto_status_routes_through_core_while_desktop_keeps_the_mutex_bound_sdk_read() {
    let command = AUTH_PRODUCT_COMMANDS_SOURCE
        .split("pub async fn matrix_crypto_status")
        .nth(1)
        .and_then(|source| source.split("pub async fn matrix_logout").next())
        .expect("matrix_crypto_status command body");
    assert!(
        command.contains("crate::bridge::session_lifecycle::crypto_status"),
        "the zero-argument command must delegate envelope/serialization to Core"
    );
    for forbidden in [
        "state.session",
        "active.client",
        "cross_signing_status",
        "CrossSigningStatus",
        "MatrixIpcError",
    ] {
        assert!(
            !command.contains(forbidden),
            "matrix_crypto_status command must not reclaim desktop crypto ownership: {forbidden}"
        );
    }

    assert_eq!(
        crypto_cross_signing_state(false, false, false, false),
        PlatformCryptoCrossSigningState::NotSetUp
    );
    assert_eq!(
        crypto_cross_signing_state(false, true, false, false),
        PlatformCryptoCrossSigningState::Partial
    );
    assert_eq!(
        crypto_cross_signing_state(true, true, true, true),
        PlatformCryptoCrossSigningState::Ready
    );

    let product_source = include_str!("product.rs");
    let projection = product_source
        .split("pub(crate) async fn crypto_status_projection")
        .nth(1)
        .and_then(|source| {
            source
                .split("/// Read the exact legacy cross-signing observation")
                .next()
        })
        .expect("desktop crypto projection must remain isolated");
    let lock = projection
        .find("self.session.lock().await")
        .expect("crypto projection must take the existing auth mutex");
    let sample = projection
        .find("cross_signing_status().await")
        .expect("crypto projection must sample only the existing SDK status");
    assert!(
        lock < sample,
        "the existing auth mutex must remain held while crypto status is awaited"
    );
    assert!(
        !projection.contains("drop(session)"),
        "crypto status must not transfer or release session ownership before sampling"
    );
    for forbidden in [
        "MatrixIpcError",
        "diagnostic_id",
        "request_user_identity",
        "bootstrap_cross_signing",
        "store_key",
    ] {
        assert!(
            !projection.contains(forbidden),
            "desktop crypto projection must stay read-only and string-free: {forbidden}"
        );
    }
}

#[test]
fn cross_signing_status_routes_only_through_core_and_holds_the_auth_mutex_across_both_sdk_reads() {
    let command_source = include_str!("../cross_signing/product_commands.rs");
    let command = command_source
        .split("pub async fn matrix_cross_signing_status")
        .nth(1)
        .and_then(|source| {
            source
                .split("pub async fn matrix_cross_signing_setup")
                .next()
        })
        .expect("cross-signing status command body");
    assert!(
        command.contains("crate::bridge::cross_signing_status::cross_signing_status"),
        "status handler must delegate Core envelope/serialization to its strict bridge"
    );
    assert!(
        command.contains("core: State<'_, Arc<synara_core::Core>>"),
        "status handler takes only the managed Core state"
    );
    for forbidden in [
        "MatrixAuthState",
        "state.session",
        "active.client",
        "live_cross_signing_status",
        "request_user_identity",
        "MatrixIpcError",
    ] {
        assert!(
            !command.contains(forbidden),
            "Tauri status handler must not reclaim desktop SDK ownership: {forbidden}"
        );
    }

    let product_source = include_str!("product.rs");
    let projection = product_source
        .split("pub(crate) async fn cross_signing_status_projection")
        .nth(1)
        .and_then(|source| source.split("/// Read secret-storage status").next())
        .expect("desktop cross-signing projection must remain isolated");
    let lock = projection
        .find("self.session.lock().await")
        .expect("cross-signing projection must take the existing auth mutex");
    let private_status = projection
        .find("cross_signing_status().await")
        .expect("projection must retain the existing private status observation");
    let identity_query = projection
        .find("request_user_identity(user_id)")
        .expect("projection must retain the existing desktop-owned identity query");
    assert!(
        lock < private_status && private_status < identity_query,
        "the auth mutex must be acquired before and held across both legacy SDK awaits"
    );
    for forbidden in [
        "drop(session)",
        "client.clone",
        "clone().request_user_identity",
    ] {
        assert!(
            !projection.contains(forbidden),
            "cross-signing observation must not clone/drop/reorder the legacy mutex owner: {forbidden}"
        );
    }
    for forbidden in [
        "MatrixIpcError",
        "diagnostic_id",
        "with_diagnostic",
        "bootstrap_cross_signing",
        "recovery",
        "secret_storage",
    ] {
        assert!(
            !projection.contains(forbidden),
            "desktop projection must be a string-free read observation only: {forbidden}"
        );
    }
}

#[test]
fn secret_storage_status_routes_only_through_core_and_preserves_desktop_observation_ownership() {
    let command_source = include_str!("../secret_storage/product_commands.rs");
    let command = command_source
        .split("pub async fn matrix_secret_storage_status")
        .nth(1)
        .and_then(|source| {
            source
                .split("pub async fn matrix_secret_storage_bootstrap")
                .next()
        })
        .expect("secret-storage status command body");
    assert!(
        command.contains("crate::bridge::secret_storage_status::secret_storage_status"),
        "status handler must delegate Core envelope/serialization to its strict bridge"
    );
    assert!(
        command.contains("core: State<'_, Arc<synara_core::Core>>"),
        "status handler takes only managed Core state"
    );
    for forbidden in [
        "MatrixAuthState",
        "state.session",
        "active.client",
        "live_secret_storage::status",
        "matrix_secret_storage_bootstrap",
        "matrix_secret_storage_unlock",
        "matrix_secret_storage_reset",
        "MatrixIpcError",
    ] {
        assert!(
            !command.contains(forbidden),
            "Tauri status handler must not reclaim desktop SDK ownership or writers: {forbidden}"
        );
    }

    let product_source = include_str!("product.rs");
    let projection = product_source
        .split("pub(crate) async fn secret_storage_status_projection")
        .nth(1)
        .and_then(|source| source.split("/// Read the upload-size config").next())
        .expect("desktop secret-storage projection must remain isolated");
    let lock = projection
        .find("self.session.lock().await")
        .expect("secret-storage projection must take the existing auth mutex");
    let observation = projection
        .find("live_secret_storage::status(&active.client, active.sync.session_generation())")
        .expect("projection must retain the existing desktop secret-storage status observation");
    assert!(
        lock < observation,
        "the existing auth mutex must be acquired before and held through status observation"
    );
    for forbidden in [
        "drop(session)",
        "client.clone",
        "matrix_secret_storage_bootstrap",
        "matrix_secret_storage_unlock",
        "matrix_secret_storage_reset",
        "MatrixIpcError",
        "with_diagnostic",
    ] {
        assert!(
            !projection.contains(forbidden),
            "secret-storage observation must remain a closed read projection: {forbidden}"
        );
    }

    for (diagnostic_id, expected) in [
        (
            "v-crypto.4-status-default-key-failed",
            PlatformSecretStorageStatusError::DefaultKeyLoadFailed,
        ),
        (
            "v-crypto.4-status-key-info-failed",
            PlatformSecretStorageStatusError::KeyInfoLoadFailed,
        ),
        (
            "v-crypto.4-status-secret-check-failed",
            PlatformSecretStorageStatusError::SecretCheckFailed,
        ),
        (
            "unexpected-private-diagnostic",
            PlatformSecretStorageStatusError::InvalidSnapshot,
        ),
    ] {
        assert_eq!(
            map_secret_storage_status_error(MatrixAuthCommandError::new(
                "Recovery",
                "Native secret storage status is unavailable.",
                diagnostic_id,
            )),
            expected,
            "desktop error text must reduce only to the closed Platform failure"
        );
    }
}

#[test]
fn secret_storage_desktop_reducer_covers_every_state_and_fixed_missing_secret_bit() {
    let states = [
        (
            NativeSecretStorageState::Unavailable,
            false,
            NativeSecretStorageAction::UnlockRequired,
        ),
        (
            NativeSecretStorageState::NotSetUp,
            false,
            NativeSecretStorageAction::BootstrapRequired,
        ),
        (
            NativeSecretStorageState::Locked,
            false,
            NativeSecretStorageAction::UnlockRequired,
        ),
        (
            NativeSecretStorageState::Ready,
            true,
            NativeSecretStorageAction::None,
        ),
    ];
    for (state, unlocked, action) in states {
        for bits in 0_u8..16 {
            let known = [
                NativeMissingSecret::CrossSigningMaster,
                NativeMissingSecret::CrossSigningSelfSigning,
                NativeMissingSecret::CrossSigningUserSigning,
                NativeMissingSecret::EncryptionBackup,
            ];
            let missing_secrets = known
                .iter()
                .enumerate()
                .filter_map(|(index, missing)| (bits & (1 << index) != 0).then_some(*missing))
                .collect();
            let projection = platform_secret_storage_status(NativeSecretStorageStatus {
                session_generation: 9,
                state,
                exists: true,
                unlocked,
                default_key_set: true,
                passphrase_configured: true,
                bootstrap_ready: true,
                missing_secrets,
                action,
            })
            .expect("every existing state/missing-secret projection is closed and valid");
            let missing = projection.missing_secrets();
            assert_eq!(missing.cross_signing_master(), bits & 1 != 0);
            assert_eq!(missing.cross_signing_self_signing(), bits & 2 != 0);
            assert_eq!(missing.cross_signing_user_signing(), bits & 4 != 0);
            assert_eq!(missing.encryption_backup(), bits & 8 != 0);
        }
    }

    assert_eq!(
        platform_secret_storage_status(NativeSecretStorageStatus {
            session_generation: 9,
            state: NativeSecretStorageState::Ready,
            exists: true,
            unlocked: false,
            default_key_set: true,
            passphrase_configured: true,
            bootstrap_ready: true,
            missing_secrets: Vec::new(),
            action: NativeSecretStorageAction::None,
        }),
        Err(PlatformSecretStorageStatusError::InvalidSnapshot)
    );
}

#[test]
fn missing_active_identity_has_clear_restore_error() {
    let root = std::env::temp_dir().join(format!("synara-d0.1-missing-{}", std::process::id()));
    let error = read_active_identity(&root).unwrap_err();
    assert_eq!(error.code, "Forbidden");
    assert_eq!(error.diagnostic_id, "d0.1-active-session-missing");
    assert!(error.message.contains("No persisted native Matrix session"));
}

#[test]
fn active_identity_round_trip_contains_only_identity() {
    let root = std::env::temp_dir().join(format!("synara-d0.1-identity-{}", std::process::id()));
    let identity = MatrixLoginIdentity {
        user_id: "@alice:example.org".into(),
        device_id: "DEVICE".into(),
        homeserver_url: "https://matrix.example.org".into(),
    };
    write_active_identity(&root, &identity).unwrap();
    assert_eq!(read_active_identity(&root).unwrap(), identity);
    remove_active_identity(&root).unwrap();
    let _ = fs::remove_dir_all(root);
}

#[test]
fn session_generations_are_monotonic() {
    let state = MatrixAuthState::new();
    assert_eq!(state.current_generation(), 0);
    assert_eq!(state.next_generation(), 1);
    assert_eq!(state.next_generation(), 2);
    assert_eq!(state.current_generation(), 2);
}

#[test]
fn send_result_serialization_is_privacy_safe() {
    let result = MatrixSendTextResult {
        room_id: "!room:example.org".into(),
        event_id: "$event:example.org".into(),
        local_txn_id: "local-txn-1".into(),
        status: "sent",
    };
    let json = serde_json::to_string(&result).unwrap();
    assert_eq!(
        json,
        r#"{"roomId":"!room:example.org","eventId":"$event:example.org","localTxnId":"local-txn-1","status":"sent"}"#
    );
    assert!(!json.contains("token"));
    assert!(!json.contains("ciphertext"));
}

#[test]
fn sticker_content_preserves_mxc_info_and_reply() {
    let content = sticker_content(
        "cat".into(),
        "mxc://example.org/sticker1".into(),
        Some(128),
        Some(128),
        Some("image/png".into()),
        Some(2048),
        Some("$event:example.org".parse().unwrap()),
        None,
    )
    .unwrap();
    let json = serde_json::to_value(&content).unwrap();
    assert_eq!(json["body"], "cat");
    assert_eq!(json["url"], "mxc://example.org/sticker1");
    assert_eq!(json["info"]["w"], 128);
    assert_eq!(json["info"]["h"], 128);
    assert_eq!(json["info"]["mimetype"], "image/png");
    assert_eq!(json["info"]["size"], 2048);
    assert_eq!(
        json["m.relates_to"]["m.in_reply_to"]["event_id"],
        "$event:example.org"
    );
    assert!(json.get("msgtype").is_none());
    assert!(!json.to_string().contains("token"));
}

#[test]
fn sticker_content_emits_thread_relation() {
    let threaded = sticker_content(
        "thread sticker".into(),
        "mxc://example.org/s".into(),
        None,
        None,
        None,
        None,
        Some("$child:example.org".parse().unwrap()),
        Some("$root:example.org".parse().unwrap()),
    )
    .unwrap();
    let json = serde_json::to_value(&threaded).unwrap();
    assert_eq!(json["m.relates_to"]["rel_type"], "m.thread");
    assert_eq!(json["m.relates_to"]["event_id"], "$root:example.org");
    assert_eq!(
        json["m.relates_to"]["m.in_reply_to"]["event_id"],
        "$child:example.org"
    );
}

#[test]
fn sticker_content_rejects_invalid_body_and_mxc() {
    let empty = sticker_content(
        "  ".into(),
        "mxc://example.org/s".into(),
        None,
        None,
        None,
        None,
        None,
        None,
    )
    .unwrap_err();
    assert_eq!(empty.diagnostic_id, "v-send-sticker-invalid-body");

    let bad_mxc = sticker_content(
        "ok".into(),
        "https://evil.example/img.png".into(),
        None,
        None,
        None,
        None,
        None,
        None,
    )
    .unwrap_err();
    assert_eq!(bad_mxc.diagnostic_id, "v-send-sticker-invalid-mxc");
}

#[test]
fn message_content_preserves_type_html_mentions_and_reply() {
    let plain = message_content("hello".into(), None, None, None, false, None, None).unwrap();
    let plain_json = serde_json::to_value(plain).unwrap();
    assert_eq!(plain_json["body"], "hello");
    assert_eq!(plain_json["msgtype"], "m.text");
    assert_eq!(plain_json["m.mentions"], serde_json::json!({}));
    assert!(plain_json.get("formatted_body").is_none());

    let reply = message_content(
        "reply".into(),
        Some("m.emote".into()),
        Some("<strong>reply</strong>".into()),
        Some(vec!["@alice:example.org".into()]),
        true,
        Some("$event:example.org".parse().unwrap()),
        None,
    )
    .unwrap();
    let reply_json = serde_json::to_value(reply).unwrap();
    assert_eq!(reply_json["msgtype"], "m.emote");
    assert_eq!(reply_json["format"], "org.matrix.custom.html");
    assert_eq!(reply_json["formatted_body"], "<strong>reply</strong>");
    assert_eq!(
        reply_json["m.mentions"],
        serde_json::json!({
            "user_ids": ["@alice:example.org"],
            "room": true
        })
    );
    assert_eq!(
        reply_json["m.relates_to"]["m.in_reply_to"]["event_id"],
        "$event:example.org"
    );
    assert!(reply_json["m.relates_to"].get("rel_type").is_none());

    let notice = message_content(
        "notice".into(),
        Some("m.notice".into()),
        None,
        None,
        false,
        None,
        None,
    )
    .unwrap();
    assert_eq!(serde_json::to_value(notice).unwrap()["msgtype"], "m.notice");
}

#[test]
fn message_content_emits_thread_relation_for_in_thread_reply() {
    let threaded = message_content(
        "in thread".into(),
        Some("m.text".into()),
        None,
        None,
        false,
        Some("$child:example.org".parse().unwrap()),
        Some("$root:example.org".parse().unwrap()),
    )
    .unwrap();
    let json = serde_json::to_value(threaded).unwrap();
    assert_eq!(json["m.relates_to"]["rel_type"], "m.thread");
    assert_eq!(json["m.relates_to"]["event_id"], "$root:example.org");
    assert_eq!(
        json["m.relates_to"]["m.in_reply_to"]["event_id"],
        "$child:example.org"
    );
    // Genuine reply in thread — is_falling_back omitted/false (serde skip default).
    assert!(
        json["m.relates_to"]
            .get("is_falling_back")
            .map(|v| v == false)
            .unwrap_or(true),
        "is_falling_back must be false/absent for Thread::reply"
    );
}

#[test]
fn message_content_emits_thread_without_fallback_when_only_root() {
    let root_only = message_content(
        "start".into(),
        None,
        None,
        None,
        false,
        None,
        Some("$root:example.org".parse().unwrap()),
    )
    .unwrap();
    let json = serde_json::to_value(root_only).unwrap();
    assert_eq!(json["m.relates_to"]["rel_type"], "m.thread");
    assert_eq!(json["m.relates_to"]["event_id"], "$root:example.org");
    assert!(json["m.relates_to"].get("m.in_reply_to").is_none());
}

#[test]
fn message_content_rejects_invalid_type_and_mentions() {
    let invalid_type = message_content(
        "body".into(),
        Some("m.image".into()),
        None,
        None,
        false,
        None,
        None,
    )
    .unwrap_err();
    assert_eq!(invalid_type.diagnostic_id, "v-send.4-invalid-message-type");

    let invalid_mention = message_content(
        "body".into(),
        None,
        None,
        Some(vec!["not-a-user".into()]),
        false,
        None,
        None,
    )
    .unwrap_err();
    assert_eq!(
        invalid_mention.diagnostic_id,
        "v-send.4-invalid-mention-user-id"
    );
}

#[test]
fn edit_message_content_emits_m_replace_with_new_content() {
    let edited = edit_message_content(
        "corrected".into(),
        Some("m.text".into()),
        Some("<p>corrected</p>".into()),
        Some(vec!["@alice:example.org".into()]),
        true,
        "$original:example.org".parse().unwrap(),
    )
    .unwrap();
    let json = serde_json::to_value(edited).unwrap();
    // Replacement relation targets the original event.
    assert_eq!(json["m.relates_to"]["rel_type"], "m.replace");
    assert_eq!(json["m.relates_to"]["event_id"], "$original:example.org");
    // Fallback body is `* {plain}`.
    assert_eq!(json["body"], "* corrected");
    // Real body/html/mentions live in m.new_content.
    assert_eq!(json["m.new_content"]["body"], "corrected");
    assert_eq!(json["m.new_content"]["formatted_body"], "<p>corrected</p>");
    assert_eq!(
        json["m.new_content"]["m.mentions"]["user_ids"][0],
        "@alice:example.org"
    );
    assert_eq!(json["m.new_content"]["m.mentions"]["room"], true);
    // The fallback content mentions are filtered to only *new* mentions; since the
    // replacement metadata carries the same mentions, none remain in the fallback.
    assert!(json["m.mentions"]
        .get("user_ids")
        .map(|v| v.as_array().is_none_or(|a| a.is_empty()))
        .unwrap_or(true));
}

#[test]
fn edit_message_content_rejects_invalid_event_id_and_type() {
    let invalid_event = parse_edit_event_id("not-an-event".into()).unwrap_err();
    assert_eq!(
        invalid_event.diagnostic_id,
        "v-send.r-edit-invalid-event-id"
    );

    let invalid_type = edit_message_content(
        "body".into(),
        Some("m.image".into()),
        None,
        None,
        false,
        "$original:example.org".parse().unwrap(),
    )
    .unwrap_err();
    assert_eq!(invalid_type.diagnostic_id, "v-send.4-invalid-message-type");
}

#[test]
fn send_input_parsers_reject_invalid_ids() {
    assert_eq!(
        parse_send_room_id("not-a-room").unwrap_err().diagnostic_id,
        "d0.4-send-invalid-room-id"
    );
    assert_eq!(
        parse_reply_event_id(Some("not-an-event".into()))
            .unwrap_err()
            .diagnostic_id,
        "d0.4-send-invalid-reply-event-id"
    );
    assert_eq!(
        parse_thread_root_event_id(Some("not-an-event".into()))
            .unwrap_err()
            .diagnostic_id,
        "v-send.5-invalid-thread-root-event-id"
    );
    assert_eq!(
        parse_transaction_id(Some(String::new()))
            .unwrap_err()
            .diagnostic_id,
        "d0.4-send-invalid-transaction-id"
    );
}

#[test]
fn display_name_parser_handles_removal_and_trim() {
    // Empty / whitespace-only → removal (None).
    assert_eq!(parse_display_name("").unwrap(), None);
    assert_eq!(parse_display_name("   ").unwrap(), None);
    // Non-empty → trimmed Some.
    assert_eq!(
        parse_display_name("  Alice  ").unwrap(),
        Some("Alice".to_owned())
    );
    assert_eq!(
        parse_display_name("Alice").unwrap(),
        Some("Alice".to_owned())
    );
}

#[test]
fn display_name_parser_rejects_oversized_names() {
    let long = "a".repeat(256);
    assert_eq!(
        parse_display_name(&long).unwrap_err().diagnostic_id,
        "v-send.r-avatar-display-name-too-long"
    );
}

#[test]
fn avatar_mxc_parser_handles_removal_and_valid_uri() {
    // Empty / whitespace-only → removal (None).
    assert_eq!(parse_avatar_mxc("").unwrap(), None);
    assert_eq!(parse_avatar_mxc("   ").unwrap(), None);
    // Valid mxc → Some.
    let parsed = parse_avatar_mxc("mxc://example.org/abc123").unwrap();
    assert_eq!(parsed.unwrap().to_string(), "mxc://example.org/abc123");
}

#[test]
fn avatar_mxc_parser_rejects_invalid_uri() {
    assert_eq!(
        parse_avatar_mxc("not-an-mxc").unwrap_err().diagnostic_id,
        "v-send.r-avatar-invalid-mxc"
    );
    assert_eq!(
        parse_avatar_mxc("https://example.org/x.png")
            .unwrap_err()
            .diagnostic_id,
        "v-send.r-avatar-invalid-mxc"
    );
}

#[test]
fn avatar_mime_validator_accepts_images_only() {
    assert_eq!(
        validate_avatar_mime("image/png").unwrap().essence_str(),
        "image/png"
    );
    assert_eq!(
        validate_avatar_mime("image/jpeg").unwrap().essence_str(),
        "image/jpeg"
    );
    assert_eq!(
        validate_avatar_mime("image/webp").unwrap().essence_str(),
        "image/webp"
    );
    assert_eq!(
        validate_avatar_mime("text/plain")
            .unwrap_err()
            .diagnostic_id,
        "v-send.r-avatar-upload-invalid-mime"
    );
    assert_eq!(
        validate_avatar_mime("").unwrap_err().diagnostic_id,
        "v-send.r-avatar-upload-invalid-mime"
    );
}

#[test]
fn avatar_error_mapping_is_stable() {
    assert_eq!(
        map_avatar_error("v-send.r-avatar-invalid-mxc").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_avatar_error("v-send.r-avatar-upload-too-large").code,
        "InvalidRequest"
    );
    assert_eq!(map_avatar_error("unknown").code, "Unknown");
}

#[test]
fn room_leave_validates_ids_and_maps_errors() {
    assert_eq!(
        parse_room_leave_id("not-a-room").unwrap_err().diagnostic_id,
        "v-rooms-room-leave-invalid-room"
    );
    assert_eq!(
        parse_room_leave_id("  !room:example.org  ")
            .unwrap()
            .to_string(),
        "!room:example.org"
    );
    assert_eq!(
        map_room_leave_error("v-rooms-room-leave-room-not-found").code,
        "NotFound"
    );
    assert_eq!(
        map_room_leave_error("v-rooms-room-leave-failed").code,
        "Unknown"
    );
}

#[test]
fn room_leave_command_owns_sdk_leave_without_a_js_fallback() {
    let product = PRODUCT_SOURCE;
    let command = product
        .split("pub async fn matrix_room_leave")
        .nth(1)
        .expect("room leave command");
    let command = command
        .split("#[tauri::command]")
        .next()
        .expect("room leave command body");
    assert!(command.contains("crate::bridge::room_leave_join::room_leave"));
    assert!(!command.contains("mx.leave"));
}

#[test]
fn room_create_builds_sdk_request_and_native_initial_state() {
    let request = build_room_create_request(MatrixRoomCreateRequest {
        name: Some("  Native room  ".into()),
        topic: Some("topic".into()),
        room_version: Some("11".into()),
        room_alias_name: Some("native-room".into()),
        is_direct: false,
        invite: vec!["@alice:example.org".into()],
        visibility: Some(MatrixRoomCreateVisibility::Public),
        preset: Some(MatrixRoomCreatePreset::Public),
        creation_content: Some(MatrixRoomCreateContent {
            room_type: Some("m.space".into()),
            federate: Some(false),
            additional_creators: Some(vec!["@bob:example.org".into()]),
        }),
        encryption: true,
        join_rule: Some("restricted".into()),
        knock: false,
        parent_room_id: Some("!parent:example.org".into()),
        power_level_content_override: Some(MatrixRoomCreatePowerLevels {
            events_default: Some(50),
            events: BTreeMap::new(),
        }),
    })
    .unwrap();
    assert_eq!(request.name.as_deref(), Some("Native room"));
    assert_eq!(request.room_version.as_ref().unwrap().as_str(), "11");
    let creation_content: serde_json::Value =
        serde_json::from_str(request.creation_content.as_ref().unwrap().json().get()).unwrap();
    assert_eq!(creation_content["type"], "m.space");
    assert_eq!(creation_content["m.federate"], false);
    assert_eq!(
        creation_content["additional_creators"][0],
        "@bob:example.org"
    );
    let power_levels: serde_json::Value = serde_json::from_str(
        request
            .power_level_content_override
            .as_ref()
            .unwrap()
            .json()
            .get(),
    )
    .unwrap();
    assert_eq!(power_levels["events_default"], 50);
    let initial_state = request
        .initial_state
        .iter()
        .map(|event| serde_json::from_str::<serde_json::Value>(event.json().get()).unwrap())
        .collect::<Vec<_>>();
    assert!(initial_state
        .iter()
        .any(|event| event["type"] == "m.room.encryption"));
    assert_eq!(
        initial_state
            .iter()
            .find(|event| event["type"] == "m.room.join_rules")
            .unwrap()["content"]["allow"][0]["room_id"],
        "!parent:example.org"
    );
}

#[test]
fn room_create_validation_and_error_maps_are_fail_closed() {
    let mut request = MatrixRoomCreateRequest {
        name: Some("room".into()),
        topic: None,
        room_version: Some(String::new()),
        room_alias_name: None,
        is_direct: false,
        invite: vec![],
        visibility: None,
        preset: None,
        creation_content: None,
        encryption: false,
        join_rule: None,
        knock: false,
        parent_room_id: None,
        power_level_content_override: None,
    };
    assert_eq!(
        build_room_create_request(request.clone())
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-room-create-invalid-room-version"
    );

    request.room_version = None;
    request.join_rule = Some("restricted".into());
    assert_eq!(
        build_room_create_request(request.clone())
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-room-create-missing-restricted-parent"
    );

    request.join_rule = None;
    request.invite = vec!["not-a-user".into()];
    assert_eq!(
        build_room_create_request(request)
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-room-create-invalid-invite"
    );
    assert_eq!(
        map_room_create_error("v-rooms-room-create-invalid-parent").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_create_error("v-rooms-room-create-failed").code,
        "Unknown"
    );
}

#[test]
fn room_create_command_owns_sdk_create_without_a_js_fallback() {
    let product = PRODUCT_SOURCE;
    let command = product
        .split("pub async fn matrix_room_create")
        .nth(1)
        .expect("room create command");
    let command = command
        .split("#[tauri::command]")
        .next()
        .expect("room create command body");
    assert!(command.contains("create_room(request)"));
    assert!(!command.contains("mx.createRoom"));
}

#[test]
fn room_join_validates_ids_aliases_and_via_servers() {
    assert_eq!(
        parse_room_join_target("not-a-room")
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-room-join-invalid-room"
    );
    assert_eq!(
        parse_room_join_target("  !room:example.org  ")
            .unwrap()
            .to_string(),
        "!room:example.org"
    );
    assert_eq!(
        parse_room_join_target("#alias:example.org")
            .unwrap()
            .to_string(),
        "#alias:example.org"
    );
    assert_eq!(parse_room_join_via_servers(None).unwrap().len(), 0);
    let via =
        parse_room_join_via_servers(Some(&[" example.org ".to_owned(), "[::1]:8448".to_owned()]))
            .unwrap();
    assert_eq!(via[0].to_string(), "example.org");
    assert_eq!(via[1].to_string(), "[::1]:8448");
    assert_eq!(
        parse_room_join_via_servers(Some(&["not a server".to_owned()]))
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-room-join-invalid-via-server"
    );
}

#[test]
fn room_join_error_mapping_is_stable() {
    assert_eq!(
        map_room_join_error("v-rooms-room-join-invalid-room").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_join_error("v-rooms-room-join-invalid-via-server").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_join_error("v-rooms-room-join-failed").code,
        "Unknown"
    );
}

#[test]
fn room_join_command_owns_sdk_join_without_a_js_fallback() {
    let product = PRODUCT_SOURCE;
    let command = product
        .split("pub async fn matrix_room_join")
        .nth(1)
        .expect("room join command");
    let command = command
        .split("#[tauri::command]")
        .next()
        .expect("room join command body");
    assert!(command.contains("crate::bridge::room_leave_join::room_join"));
    assert!(!command.contains("mx.joinRoom"));
}

#[test]
fn room_members_snapshot_validates_and_maps_errors_fail_closed() {
    assert_eq!(
        parse_room_members_room_id("not-a-room").unwrap_err(),
        "v-rooms-members-read-invalid-room"
    );
    assert_eq!(
        parse_room_members_room_id("  !room:example.org  ")
            .unwrap()
            .to_string(),
        "!room:example.org"
    );
    assert_eq!(
        map_room_members_error("v-rooms-members-read-invalid-room").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_members_error("v-rooms-members-read-room-not-found").code,
        "NotFound"
    );
    assert_eq!(
        map_room_members_error("v-rooms-members-read-members-failed").code,
        "Unknown"
    );
}

#[test]
fn room_members_snapshot_owns_live_sdk_members_without_js_fallback() {
    let product = PRODUCT_SOURCE;
    let command = product
        .split("pub async fn matrix_room_members_snapshot")
        .nth(1)
        .expect("room members snapshot command");
    let command = command
        .split("#[tauri::command]")
        .next()
        .expect("room members snapshot command body");
    assert!(command.contains("members(RoomMemberships::empty())"));
    assert!(!command.contains("getMembers"));
    assert!(!command.contains("matrix-js-sdk"));
}

#[test]
fn power_level_and_creator_snapshots_have_fixed_wire_shapes() {
    let power_levels = NativeRoomPowerLevelsSnapshot {
        status: "ok",
        session_generation: 7,
        room_id: "!room:example.org".to_owned(),
        event_type: "m.room.power_levels",
        state_key: "",
        content: serde_json::json!({
            "users_default": 0,
            "users": { "@alice:example.org": 100 },
            "retained": { "value": true },
        }),
    };
    assert_eq!(
        serde_json::to_value(power_levels).unwrap(),
        serde_json::json!({
            "status": "ok",
            "sessionGeneration": 7,
            "roomId": "!room:example.org",
            "eventType": "m.room.power_levels",
            "stateKey": "",
            "content": {
                "users_default": 0,
                "users": { "@alice:example.org": 100 },
                "retained": { "value": true },
            },
        })
    );

    let creators = NativeRoomCreatorsSnapshot {
        status: "ok",
        session_generation: 7,
        room_id: "!room:example.org".to_owned(),
        event_type: "m.room.create",
        state_key: "",
        creators: vec!["@alice:example.org".to_owned()],
    };
    assert_eq!(
        serde_json::to_value(creators).unwrap(),
        serde_json::json!({
            "status": "ok",
            "sessionGeneration": 7,
            "roomId": "!room:example.org",
            "eventType": "m.room.create",
            "stateKey": "",
            "creators": ["@alice:example.org"],
        })
    );

    let tags = NativeRoomPowerLevelTagsSnapshot {
        status: "ok",
        session_generation: 7,
        room_id: "!room:example.org".to_owned(),
        event_type: "in.synara.room.power_level_tags",
        state_key: "",
        content: serde_json::json!({
            "100": { "name": "Admin", "color": "#0088ff" },
        }),
    };
    assert_eq!(
        serde_json::to_value(tags).unwrap(),
        serde_json::json!({
            "status": "ok",
            "sessionGeneration": 7,
            "roomId": "!room:example.org",
            "eventType": "in.synara.room.power_level_tags",
            "stateKey": "",
            "content": {
                "100": { "name": "Admin", "color": "#0088ff" },
            },
        })
    );
}

#[test]
fn creator_projection_preserves_supported_room_creator_semantics() {
    let event = serde_json::json!({
        "sender": "@alice:example.org",
        "content": {
            "room_version": "12",
            "additional_creators": [
                "@bob:example.org",
                "@alice:example.org",
            ],
        },
    });
    assert_eq!(
        project_room_creators(&event).unwrap(),
        vec!["@alice:example.org", "@bob:example.org"]
    );

    let legacy_event = serde_json::json!({
        "sender": "@alice:example.org",
        "content": { "room_version": "11" },
    });
    assert!(project_room_creators(&legacy_event).unwrap().is_empty());

    let malformed = serde_json::json!({
        "sender": "not-a-user",
        "content": { "room_version": "12" },
    });
    assert!(project_room_creators(&malformed).is_err());
}

#[test]
fn power_level_snapshot_validation_preserves_unknown_fields_and_rejects_bad_maps() {
    let content = serde_json::json!({
        "users_default": 0,
        "events": { "m.room.name": 50 },
        "notifications": { "room": 50 },
        "retained": { "value": [true, "unchanged"] },
    });
    assert!(validate_power_levels_snapshot_content(&content).is_ok());
    assert_eq!(content["retained"]["value"][1], "unchanged");

    assert!(validate_power_levels_snapshot_content(&serde_json::json!({
        "users": { "@alice:example.org": 1.5 },
    }))
    .is_err());
    assert!(validate_power_levels_snapshot_content(&serde_json::json!({
        "events": [],
    }))
    .is_err());
    assert!(validate_power_levels_snapshot_content(&serde_json::json!({
        "ban": 9_007_199_254_740_992_i64,
    }))
    .is_err());
}

#[test]
fn power_level_tag_snapshot_validation_preserves_metadata_and_rejects_bad_tags() {
    let content = serde_json::json!({
        "100": {
            "name": "Admin",
            "color": "#0088ff",
            "icon": {
                "key": "mxc://example.org/admin",
                "info": { "w": 32, "h": 32, "mimetype": "image/png" },
            },
        },
    });
    assert!(validate_power_level_tags_snapshot_content(&content).is_ok());
    assert_eq!(content["100"]["icon"]["key"], "mxc://example.org/admin");
    assert!(validate_power_level_tags_snapshot_content(&serde_json::json!({})).is_ok());
    assert!(
        validate_power_level_tags_snapshot_content(&serde_json::json!({
            "01": { "name": "Invalid key" },
        }))
        .is_err()
    );
    assert!(
        validate_power_level_tags_snapshot_content(&serde_json::json!({
            "100": { "name": "   " },
        }))
        .is_err()
    );
    assert!(
        validate_power_level_tags_snapshot_content(&serde_json::json!({
            "100": { "name": "Invalid icon", "icon": { "info": [] } },
        }))
        .is_err()
    );
}

#[test]
fn power_read_commands_are_registered_and_use_live_room_state() {
    let product = PRODUCT_SOURCE;
    let lib = include_str!("../../lib.rs");
    let build = include_str!("../../../build.rs");
    let capability = include_str!("../../../capabilities/main.json");
    for command in [
        "matrix_room_power_levels_snapshot",
        "matrix_room_creators_snapshot",
        "matrix_room_power_level_tags_snapshot",
    ] {
        let capability_id = command.replace('_', "-");
        assert!(product.contains(&format!("pub async fn {command}")));
        assert!(lib.contains(command));
        assert!(build.contains(&format!("\"{command}\"")));
        assert!(capability.contains(&format!("allow-{capability_id}")));
    }
    let power_command = product
        .split("pub async fn matrix_room_power_levels_snapshot")
        .nth(1)
        .expect("power-level read command")
        .split("#[tauri::command]")
        .next()
        .expect("power-level read command body");
    assert!(power_command.contains("read_room_state_content"));
    assert!(product.contains("get_state_event(StateEventType::from(event_type), \"\")"));
    assert!(!power_command.contains("send_state_event"));
    assert!(!power_command.contains("matrix-js-sdk"));

    let tags_command = product
        .split("pub async fn matrix_room_power_level_tags_snapshot")
        .nth(1)
        .expect("power-level tag read command")
        .split("#[tauri::command]")
        .next()
        .expect("power-level tag read command body");
    assert!(tags_command.contains("read_room_state_content"));
    assert!(!tags_command.contains("send_state_event"));
}

#[test]
fn room_moderation_validates_ids_and_power_levels() {
    assert_eq!(
        parse_room_moderation_room_id("not-a-room")
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-members-moderation-invalid-room"
    );
    assert_eq!(
        parse_room_moderation_room_id("  !room:example.org  ")
            .unwrap()
            .to_string(),
        "!room:example.org"
    );
    assert_eq!(
        parse_room_moderation_user_id("not-a-user")
            .unwrap_err()
            .diagnostic_id,
        "v-rooms-members-moderation-invalid-user"
    );
    assert_eq!(
        parse_room_moderation_user_id("  @alice:example.org  ")
            .unwrap()
            .to_string(),
        "@alice:example.org"
    );
    assert!(parse_room_moderation_power_level(100).is_ok());
    assert_eq!(
        normalize_moderation_reason(Some("  spam  ".to_owned())).as_deref(),
        Some("spam")
    );
    assert_eq!(normalize_moderation_reason(Some("   ".to_owned())), None);
}

#[test]
fn room_directory_visibility_commands_keep_the_native_owner_contract() {
    assert!(PRODUCT_SOURCE.contains("matrix_get_room_directory_visibility"));
    assert!(PRODUCT_SOURCE.contains("matrix_set_room_directory_visibility"));
    let get_command = PRODUCT_SOURCE
        .split("pub async fn matrix_get_room_directory_visibility")
        .nth(1)
        .expect("directory visibility get command")
        .split("#[tauri::command]")
        .next()
        .expect("directory visibility get command body");
    assert!(get_command.contains("get_room_visibility()"));
    let set_command = PRODUCT_SOURCE
        .split("pub async fn matrix_set_room_directory_visibility")
        .nth(1)
        .expect("directory visibility set command")
        .split("#[tauri::command]")
        .next()
        .expect("directory visibility set command body");
    assert!(!set_command.contains("get_room_visibility()"));
    assert!(set_command.contains("update_room_visibility(native_visibility)"));
    assert!(
        set_command.contains("user_can_send_state(user_id, StateEventType::RoomCanonicalAlias)")
    );
    assert!(!set_command.contains("power_levels_or_default"));
    assert!(!set_command.contains("RoomProfileIndex::set_directory_visibility"));
}

#[test]
fn room_directory_visibility_parsers_and_wire_shapes_are_strict() {
    assert_eq!(
        parse_room_directory_visibility_room_id("!room:example.org")
            .unwrap()
            .to_string(),
        "!room:example.org"
    );
    assert_eq!(
        parse_room_directory_visibility_room_id("not-a-room")
            .unwrap_err()
            .diagnostic_id,
        "v-send.r-room-profile-directory-visibility-invalid"
    );
    assert_eq!(
        parse_room_directory_visibility("public").unwrap().1,
        "public"
    );
    assert_eq!(
        parse_room_directory_visibility("private").unwrap().1,
        "private"
    );
    assert_eq!(
        parse_room_directory_visibility("unknown")
            .unwrap_err()
            .diagnostic_id,
        "v-send.r-room-profile-directory-visibility-invalid"
    );

    let read = serde_json::to_value(MatrixRoomDirectoryVisibilityResult {
        status: "ok",
        room_id: "!room:example.org".into(),
        session_generation: 7,
        visibility: "public",
    })
    .unwrap();
    assert_eq!(
        read,
        serde_json::json!({
            "status": "ok",
            "roomId": "!room:example.org",
            "sessionGeneration": 7,
            "visibility": "public"
        })
    );

    let write = serde_json::to_value(MatrixRoomDirectoryVisibilityWriteResult {
        status: "ok",
        room_id: "!room:example.org".into(),
        session_generation: 7,
        requested_visibility: "private",
    })
    .unwrap();
    assert_eq!(
        write,
        serde_json::json!({
            "status": "ok",
            "roomId": "!room:example.org",
            "sessionGeneration": 7,
            "requestedVisibility": "private"
        })
    );
}

#[test]
fn room_moderation_error_mapping_is_stable() {
    assert_eq!(
        map_room_moderation_error("v-rooms-members-moderation-invalid-room").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_moderation_error("v-rooms-members-moderation-invalid-user").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_moderation_error("v-rooms-members-moderation-invalid-power-level").code,
        "InvalidRequest"
    );
    assert_eq!(
        map_room_moderation_error("v-rooms-members-moderation-room-not-found").code,
        "NotFound"
    );
    assert_eq!(
        map_room_moderation_error("v-rooms-members-moderation-ban-failed").code,
        "Unknown"
    );
}

#[test]
fn room_moderation_commands_use_live_sdk_methods_without_js_fallbacks() {
    let product = PRODUCT_SOURCE;
    let expected_methods = [
        ("matrix_room_invite", "invite_user_by_id"),
        ("matrix_room_kick", "kick_user"),
        ("matrix_room_ban", "ban_user"),
        ("matrix_room_unban", "unban_user"),
        ("matrix_room_set_power_level", "update_power_levels"),
    ];

    for (command_name, sdk_method) in expected_methods {
        let command = product
            .split(&format!("pub async fn {command_name}"))
            .nth(1)
            .expect("moderation command");
        let command = command
            .split("#[tauri::command]")
            .next()
            .expect("moderation command body");
        assert!(command.contains(sdk_method), "{command_name} SDK method");
        assert!(!command.contains("mx."), "{command_name} JS fallback");
    }
}

#[test]
fn power_level_write_result_serializes_exact_wire_shape() {
    let result = NativePowerLevelWriteResult {
        status: "ok",
        room_id: "!room:example.org".to_owned(),
        event_type: ROOM_POWER_LEVELS_EVENT_TYPE,
        state_key: "",
        session_generation: 7,
        content: serde_json::json!({
            "users": { "@alice:example.org": 100 },
            "historical": 0,
            "retained": { "value": true },
        }),
    };
    assert_eq!(
        serde_json::to_value(result).unwrap(),
        serde_json::json!({
            "status": "ok",
            "roomId": "!room:example.org",
            "eventType": "m.room.power_levels",
            "stateKey": "",
            "sessionGeneration": 7,
            "content": {
                "users": { "@alice:example.org": 100 },
                "historical": 0,
                "retained": { "value": true },
            },
        })
    );
}

#[test]
fn power_level_content_validation_preserves_complete_policy_maps() {
    let content = serde_json::json!({
        "ban": 50,
        "historical": 0,
        "users_default": 0,
        "users": { "@alice:example.org": 100, "@bob:example.org": 25 },
        "events": { "m.room.name": 50 },
        "notifications": { "room": 50 },
        "unknown_policy_member": { "keep": ["all", "values"] },
    });
    assert!(validate_room_power_levels_content(&content).is_ok());
    assert_eq!(content["users"]["@alice:example.org"], 100);
    assert_eq!(content["unknown_policy_member"]["keep"][0], "all");

    assert!(validate_room_power_levels_content(&serde_json::json!({
        "users": { "@alice:example.org": 1.5 },
    }))
    .is_err());
    assert!(validate_room_power_levels_content(&serde_json::json!({
        "events": [],
    }))
    .is_err());
    assert!(validate_room_power_levels_content(&serde_json::json!({
        "ban": 9_007_199_254_740_992_i64,
    }))
    .is_err());
}

#[test]
fn power_level_tag_validation_preserves_icon_association_and_empty_delete_state() {
    let content = serde_json::json!({
        "100": {
            "name": "Admin",
            "color": "#0088ff",
            "icon": {
                "key": "mxc://example.org/admin",
                "info": {
                    "w": 32,
                    "h": 32,
                    "mimetype": "image/png",
                    "size": 512,
                    "xyz.amorgan.blurhash": "LEHV6nWB2yk8pyo0adR*.7kCMdnj",
                },
            },
        },
    });
    assert!(validate_power_level_tags_content(&content).is_ok());
    assert_eq!(content["100"]["icon"]["key"], "mxc://example.org/admin");
    assert!(validate_power_level_tags_content(&serde_json::json!({})).is_ok());
    assert!(validate_power_level_tags_content(&serde_json::json!({
        "01": { "name": "Invalid key" },
    }))
    .is_err());
    assert!(validate_power_level_tags_content(&serde_json::json!({
        "100": { "name": "   " },
    }))
    .is_err());
    assert!(validate_power_level_tags_content(&serde_json::json!({
        "100": { "name": "Invalid icon", "icon": { "info": [] } },
    }))
    .is_err());
}

#[test]
fn power_level_commands_are_registered_and_have_no_bulk_single_user_loop() {
    let product = PRODUCT_SOURCE;
    let lib = include_str!("../../lib.rs");
    let build = include_str!("../../../build.rs");
    for command in [
        "matrix_room_set_power_levels",
        "matrix_room_set_power_level_tags",
    ] {
        assert!(product.contains(&format!("pub async fn {command}")));
        assert!(lib.contains(command));
        assert!(build.contains(&format!("\"{command}\"")));
    }
    let bulk_command = product
        .split("pub async fn matrix_room_set_power_levels")
        .nth(1)
        .expect("bulk power-level command")
        .split("#[tauri::command]")
        .next()
        .expect("bulk power-level command body");
    assert!(!bulk_command.contains("update_power_levels"));
}

#[test]
fn v_auth_native_session_envelope_host_dual_write_is_wired() {
    let product_prod = AUTH_PRODUCT_COMMANDS_SOURCE
        .split("#[cfg(test)]")
        .next()
        .expect("product production section");

    // The hybrid desktop session envelope is the frontend bootstrap's native
    // rehydration source (desktop_get_session). It must be dual-written
    // host-side on native session install (password login + register) and
    // cleared on logout so tokens never need to appear on the login/register
    // IPC return paths.
    for marker in [
        "DesktopSessionEnvelope",
        "desktop_set_session_in_store",
        "persist_frontend_session_envelope",
        "clear_frontend_session_envelope",
    ] {
        assert!(
            product_prod.contains(marker),
            "auth product module must wire {marker}"
        );
    }

    let login_fn = product_prod
        .split("pub async fn matrix_login_password")
        .nth(1)
        .and_then(|rest| rest.split("pub async fn ").next())
        .expect("matrix_login_password body");
    assert!(
        login_fn.contains("persist_frontend_session_envelope(&client, &identity)"),
        "password login must dual-write the desktop session envelope"
    );

    let register_install_fn = product_prod
        .split("pub(super) async fn install_session_from_register_secrets")
        .nth(1)
        .and_then(|rest| rest.split("pub async fn ").next())
        .expect("install_session_from_register_secrets body");
    assert!(
        register_install_fn.contains("persist_frontend_session_envelope(&client, &identity)"),
        "register session install must dual-write the desktop session envelope"
    );

    let logout_fn = product_prod
        .split("pub async fn matrix_logout")
        .nth(1)
        .and_then(|rest| rest.split("pub async fn ").next())
        .expect("matrix_logout body");
    assert!(
        logout_fn.contains("clear_frontend_session_envelope()"),
        "logout must clear the desktop session envelope"
    );

    // The login identity DTO must never carry tokens to the frontend; the
    // host-side envelope is the only token transport.
    let product_source = include_str!("product.rs");
    let identity_fn = product_source
        .split("pub struct MatrixLoginIdentity {")
        .nth(1)
        .and_then(|rest| rest.split('}').next())
        .expect("MatrixLoginIdentity fields");
    for forbidden in ["access_token", "refresh_token"] {
        assert!(
            !identity_fn.contains(forbidden),
            "MatrixLoginIdentity must not expose {forbidden} on the login IPC"
        );
    }
}

#[test]
fn media_config_and_download_use_exact_wire_shapes() {
    let request = MatrixMediaDownloadRequest {
        content_uri: "mxc://example.org/media".to_owned(),
    };
    assert_eq!(
        serde_json::to_value(request).unwrap(),
        serde_json::json!({ "contentUri": "mxc://example.org/media" })
    );

    let config = MatrixMediaConfigResult {
        upload_size: 16 * 1024 * 1024,
    };
    assert_eq!(
        serde_json::to_value(config).unwrap(),
        serde_json::json!({ "m.upload.size": 16 * 1024 * 1024 })
    );

    let download = MatrixMediaDownloadResult {
        bytes: vec![0, 1, 255],
    };
    assert_eq!(
        serde_json::to_value(download).unwrap(),
        serde_json::json!({ "bytes": [0, 1, 255] })
    );
}

#[test]
fn media_download_uri_validation_is_bounded_and_fail_closed() {
    assert_eq!(
        parse_media_download_uri("mxc://example.org/media")
            .unwrap()
            .to_string(),
        "mxc://example.org/media"
    );

    for invalid in [
        "",
        " ",
        "https://example.org/media",
        "data:text/plain,secret",
        "javascript:alert(1)",
        "mxc://example.org/",
        "mxc://example.org/media?access_token=secret",
        "mxc://example.org/me/dia",
        &format!("mxc://example.org/{}", "a".repeat(2_100)),
    ] {
        assert_eq!(
            parse_media_download_uri(invalid).unwrap_err().diagnostic_id,
            "v-send.r-media-invalid-content-uri",
            "invalid URI should be rejected: {invalid}"
        );
    }
}

#[test]
fn media_download_size_ceiling_never_truncates() {
    assert!(validate_media_download_size(MAX_MEDIA_DOWNLOAD_BYTES).is_ok());
    assert_eq!(
        validate_media_download_size(MAX_MEDIA_DOWNLOAD_BYTES + 1)
            .unwrap_err()
            .diagnostic_id,
        "v-send.r-media-download-too-large"
    );
}

#[test]
fn media_errors_are_stable_and_privacy_safe() {
    let error = map_media_download_error("v-send.r-media-download-sdk-failed");
    let raw = serde_json::to_string(&error).unwrap();
    assert_eq!(error.code, "Unknown");
    assert_eq!(error.diagnostic_id, "v-send.r-media-download-sdk-failed");
    assert!(!raw.contains("mxc://"));
    assert!(!raw.contains("access_token"));
    assert!(!raw.contains("bytes"));
    assert!(!raw.contains("sdk error"));
}

#[tokio::test]
async fn media_config_desktop_owner_keeps_the_live_client_and_closed_no_session_error() {
    let error = MatrixAuthState::new()
        .media_config_projection()
        .await
        .expect_err("a desktop-owned SDK observation requires a live session");
    assert_eq!(
        error,
        synara_core::platform::PlatformMediaConfigError::NoSession
    );

    let product = PRODUCT_SOURCE;
    let config = product
        .split("pub async fn matrix_media_config")
        .nth(1)
        .expect("media config command");
    let config = config
        .split("#[tauri::command]")
        .next()
        .expect("media config command body");
    assert!(config.contains("crate::bridge::media_config::media_config"));
    assert!(config.contains("core: State<'_, Arc<synara_core::Core>>"));
    assert!(!config.contains("load_or_fetch_max_upload_size"));

    // The former command already cloned Client under the auth mutex and
    // released it before its cache/network read. Keep that exact safe behavior
    // in desktop ownership; Core receives only the post-load scalar projection.
    let desktop_owner = include_str!("product.rs");
    let projection = desktop_owner
        .split("pub(crate) async fn media_config_projection")
        .nth(1)
        .expect("desktop media config projection");
    let clone = projection
        .find("active.client.clone()")
        .expect("clone the live client while holding the auth mutex");
    let release = projection[clone..]
        .find("};")
        .map(|offset| clone + offset)
        .expect("close the client/mutex scope before the SDK load");
    let load = projection
        .find("load_or_fetch_max_upload_size")
        .expect("desktop owns the SDK cache/network load");
    assert!(
        clone < release && release < load,
        "media config must preserve the existing clone-then-release lock semantics"
    );
    assert!(projection.contains("PlatformMediaConfig::new(upload_size)"));
    assert!(!projection.contains("synara_core::Core"));
    assert!(!projection.contains("matrix-js-sdk"));

    let download = product
        .split("pub async fn matrix_media_download")
        .nth(1)
        .expect("media download command");
    let download = download
        .split("#[tauri::command]")
        .next()
        .expect("media download command body");
    assert!(download.contains("MediaFormat::File"));
    assert!(download.contains("get_media_content(&media_request, true)"));
    assert!(!download.contains("Thumbnail"));
    assert!(!download.contains("mxcUrlToHttp"));
}
