//! SSO / OAuth callback lifecycle (P3.3 harness foundation).
//!
//! Pure state machine for starting an SSO browser flow, accepting a callback
//! redirect, and coordinating host-side token exchange. **Never stores access
//! tokens, refresh tokens, login tokens, or authorization codes** — only
//! privacy-safe metadata (state id, IdP id, phase). No dual-backend, no
//! production Tauri commands.

use super::error::AuthError;

/// Soft cap on concurrent pending SSO attempts (UI/safety).
pub const MAX_PENDING_SSO_FLOWS: usize = 4;

/// Soft cap on state / IdP id string length.
pub const MAX_SSO_ID_CHARS: usize = 128;

/// Soft cap on redirect URL length (chars).
pub const MAX_REDIRECT_URL_CHARS: usize = 2048;

/// SSO callback lifecycle phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SsoCallbackPhase {
    /// No active SSO attempt.
    Idle,
    /// Host opened browser / system auth session; waiting for redirect.
    AwaitingBrowser,
    /// Redirect arrived; host has not yet exchanged code for session.
    CallbackReceived,
    /// Host is exchanging authorization material with homeserver/SDK.
    Exchanging,
    /// Login completed (session on SDK client; not held here).
    Succeeded,
    /// User cancelled browser/auth session.
    Cancelled,
    /// Failed (diagnostic id only).
    Failed,
}

impl SsoCallbackPhase {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::AwaitingBrowser => "awaiting_browser",
            Self::CallbackReceived => "callback_received",
            Self::Exchanging => "exchanging",
            Self::Succeeded => "succeeded",
            Self::Cancelled => "cancelled",
            Self::Failed => "failed",
        }
    }

    pub fn is_active(self) -> bool {
        matches!(
            self,
            Self::AwaitingBrowser | Self::CallbackReceived | Self::Exchanging
        )
    }

    pub fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Idle | Self::Succeeded | Self::Cancelled | Self::Failed
        )
    }
}

/// Privacy-safe outcome after a successful SSO completion signal.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SsoCallbackOutcome {
    pub session_generation: u64,
    pub op_id: u64,
    /// Optional SSO IdP id (never a secret).
    pub idp_id: Option<String>,
    /// Optional homeserver URL used for the flow (no tokens).
    pub homeserver_url: Option<String>,
}

/// Session-generation-stamped SSO callback coordinator.
#[derive(Debug, Clone, PartialEq)]
pub struct SsoCallbackFlow {
    session_generation: u64,
    phase: SsoCallbackPhase,
    /// Opaque CSRF/state identifier generated by host (not a secret token).
    state_id: Option<String>,
    idp_id: Option<String>,
    homeserver_url: Option<String>,
    /// Expected redirect base (scheme/host/path); host validates full URL.
    redirect_url: Option<String>,
    failure_diagnostic_id: Option<&'static str>,
    /// Monotonic op id for stale host completion rejection.
    op_id: u64,
    /// Count of starts in this generation (cap enforcement helper).
    starts_this_generation: u32,
}

impl SsoCallbackFlow {
    pub fn new(session_generation: u64) -> Self {
        Self {
            session_generation,
            phase: SsoCallbackPhase::Idle,
            state_id: None,
            idp_id: None,
            homeserver_url: None,
            redirect_url: None,
            failure_diagnostic_id: None,
            op_id: 0,
            starts_this_generation: 0,
        }
    }

    pub fn session_generation(&self) -> u64 {
        self.session_generation
    }

    pub fn phase(&self) -> SsoCallbackPhase {
        self.phase
    }

    pub fn state_id(&self) -> Option<&str> {
        self.state_id.as_deref()
    }

    pub fn idp_id(&self) -> Option<&str> {
        self.idp_id.as_deref()
    }

    pub fn homeserver_url(&self) -> Option<&str> {
        self.homeserver_url.as_deref()
    }

    pub fn redirect_url(&self) -> Option<&str> {
        self.redirect_url.as_deref()
    }

    pub fn failure_diagnostic_id(&self) -> Option<&'static str> {
        self.failure_diagnostic_id
    }

    pub fn op_id(&self) -> u64 {
        self.op_id
    }

    pub fn is_active(&self) -> bool {
        self.phase.is_active()
    }

    fn validate_id(label: &'static str, value: &str) -> Result<(), AuthError> {
        if value.is_empty() || value.chars().count() > MAX_SSO_ID_CHARS {
            return Err(AuthError::InvalidInput {
                diagnostic_id: label,
                reason: "empty_or_too_long_id",
            });
        }
        Ok(())
    }

    /// Redirect must be custom-scheme (`synara:` / `synara-desktop:`) or https.
    /// **Never** allow javascript: / data: / file:.
    pub fn validate_redirect_url(url: &str) -> Result<(), AuthError> {
        let url = url.trim();
        if url.is_empty() || url.chars().count() > MAX_REDIRECT_URL_CHARS {
            return Err(AuthError::InvalidInput {
                diagnostic_id: "p3.3-invalid-redirect-url",
                reason: "empty_or_too_long_redirect",
            });
        }
        let lower = url.to_ascii_lowercase();
        if lower.starts_with("javascript:")
            || lower.starts_with("data:")
            || lower.starts_with("file:")
            || lower.starts_with("http:")
        {
            return Err(AuthError::InvalidInput {
                diagnostic_id: "p3.3-forbidden-redirect-scheme",
                reason: "forbidden_redirect_scheme",
            });
        }
        if !(lower.starts_with("https://")
            || lower.starts_with("synara:")
            || lower.starts_with("synara-desktop:"))
        {
            return Err(AuthError::InvalidInput {
                diagnostic_id: "p3.3-unsupported-redirect-scheme",
                reason: "unsupported_redirect_scheme",
            });
        }
        // Reject obvious query secret keys in the *expected* redirect template.
        for needle in [
            "access_token=",
            "refresh_token=",
            "loginToken=",
            "password=",
        ] {
            if lower.contains(&needle.to_ascii_lowercase()) {
                return Err(AuthError::InvalidInput {
                    diagnostic_id: "p3.3-redirect-forbids-secrets",
                    reason: "redirect_must_not_embed_secrets",
                });
            }
        }
        Ok(())
    }

    /// Begin SSO: host will open browser. Returns `op_id`.
    pub fn begin(
        &mut self,
        state_id: impl Into<String>,
        redirect_url: impl Into<String>,
        idp_id: Option<String>,
        homeserver_url: Option<String>,
    ) -> Result<u64, AuthError> {
        if self.is_active() {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-sso-already-active",
            });
        }
        if self.starts_this_generation as usize >= MAX_PENDING_SSO_FLOWS {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-sso-start-cap",
            });
        }
        let state_id = state_id.into().trim().to_owned();
        Self::validate_id("p3.3-invalid-state-id", &state_id)?;
        let redirect_url = redirect_url.into().trim().to_owned();
        Self::validate_redirect_url(&redirect_url)?;
        if let Some(ref idp) = idp_id {
            Self::validate_id("p3.3-invalid-idp-id", idp)?;
        }
        if let Some(ref hs) = homeserver_url {
            if hs.is_empty() || !hs.starts_with("https://") {
                return Err(AuthError::InvalidInput {
                    diagnostic_id: "p3.3-invalid-homeserver-url",
                    reason: "homeserver_must_be_https",
                });
            }
        }

        self.op_id = self.op_id.saturating_add(1);
        self.starts_this_generation = self.starts_this_generation.saturating_add(1);
        self.state_id = Some(state_id);
        self.redirect_url = Some(redirect_url);
        self.idp_id = idp_id;
        self.homeserver_url = homeserver_url;
        self.failure_diagnostic_id = None;
        self.phase = SsoCallbackPhase::AwaitingBrowser;
        Ok(self.op_id)
    }

    /// Host received redirect; `state` must match pending state_id.
    ///
    /// Callers must strip authorization codes / tokens before calling — this
    /// API only accepts the privacy-safe state match.
    pub fn on_callback(&mut self, state: &str, op_id: u64) -> Result<(), AuthError> {
        if op_id != self.op_id {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-stale-sso-op",
            });
        }
        if self.phase != SsoCallbackPhase::AwaitingBrowser {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-callback-wrong-phase",
            });
        }
        let expected = self.state_id.as_deref().unwrap_or("");
        if state.trim() != expected {
            self.phase = SsoCallbackPhase::Failed;
            self.failure_diagnostic_id = Some("p3.3-state-mismatch");
            return Err(AuthError::AuthenticationRejected {
                diagnostic_id: "p3.3-state-mismatch",
            });
        }
        self.phase = SsoCallbackPhase::CallbackReceived;
        Ok(())
    }

    /// Host begins exchanging the callback for an SDK session (network).
    pub fn begin_exchange(&mut self, op_id: u64) -> Result<(), AuthError> {
        if op_id != self.op_id {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-stale-sso-op",
            });
        }
        if self.phase != SsoCallbackPhase::CallbackReceived {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-exchange-wrong-phase",
            });
        }
        self.phase = SsoCallbackPhase::Exchanging;
        Ok(())
    }

    /// Host reports successful login; clears pending metadata.
    pub fn complete_success(&mut self, op_id: u64) -> Result<SsoCallbackOutcome, AuthError> {
        if op_id != self.op_id {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-stale-sso-op",
            });
        }
        if self.phase != SsoCallbackPhase::Exchanging {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-complete-wrong-phase",
            });
        }
        let outcome = SsoCallbackOutcome {
            session_generation: self.session_generation,
            op_id: self.op_id,
            idp_id: self.idp_id.clone(),
            homeserver_url: self.homeserver_url.clone(),
        };
        self.phase = SsoCallbackPhase::Succeeded;
        self.state_id = None;
        self.redirect_url = None;
        self.failure_diagnostic_id = None;
        Ok(outcome)
    }

    pub fn cancel(&mut self, op_id: u64) -> Result<(), AuthError> {
        if op_id != self.op_id {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-stale-sso-op",
            });
        }
        if !self.is_active() {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-cancel-inactive",
            });
        }
        self.phase = SsoCallbackPhase::Cancelled;
        self.state_id = None;
        self.redirect_url = None;
        Ok(())
    }

    pub fn fail(&mut self, op_id: u64, diagnostic_id: &'static str) -> Result<(), AuthError> {
        if op_id != self.op_id {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-stale-sso-op",
            });
        }
        if !self.is_active() {
            return Err(AuthError::SdkInvariant {
                diagnostic_id: "p3.3-fail-inactive",
            });
        }
        self.phase = SsoCallbackPhase::Failed;
        self.failure_diagnostic_id = Some(diagnostic_id);
        self.state_id = None;
        self.redirect_url = None;
        Ok(())
    }

    /// Reset to Idle so another SSO attempt can start.
    pub fn reset(&mut self) {
        self.phase = SsoCallbackPhase::Idle;
        self.state_id = None;
        self.idp_id = None;
        self.homeserver_url = None;
        self.redirect_url = None;
        self.failure_diagnostic_id = None;
    }

    /// Account switch / logout: bump generation and wipe pending SSO.
    pub fn retire_generation(&mut self, new_generation: u64) {
        self.session_generation = new_generation;
        self.phase = SsoCallbackPhase::Idle;
        self.state_id = None;
        self.idp_id = None;
        self.homeserver_url = None;
        self.redirect_url = None;
        self.failure_diagnostic_id = None;
        self.starts_this_generation = 0;
        // keep op_id monotonic across generations
    }

    /// Invariant: this coordinator never holds token-like field names in state.
    pub fn never_stores_tokens(&self) -> bool {
        true
    }
}
