"$schema" = "../../gen/schemas/schema.json"

[[permission]]
identifier = "allow-matrix-backup-repair"
description = "Enables the matrix_backup_repair command without any pre-configured scope."
commands.allow = ["matrix_backup_repair"]

[[permission]]
identifier = "deny-matrix-backup-repair"
description = "Denies the matrix_backup_repair command without any pre-configured scope."
commands.deny = ["matrix_backup_repair"]
