import test from "node:test";
import assert from "node:assert/strict";

import { inspectSynapseHarness } from "../check-synapse-integration-harness.mjs";

const valid = {
  compose: `
    image: matrixdotorg/synapse:v1.156.0
    image: postgres:16.9-bookworm
    POSTGRES_PASSWORD: \${SYNARA_POSTGRES_PASSWORD:?generated by scripts/synapse-integration.sh}
    UID: \${SYNARA_UID:?generated by scripts/synapse-integration.sh}
    GID: \${SYNARA_GID:?generated by scripts/synapse-integration.sh}
    - "127.0.0.1:\${SYNARA_PORT:-8008}:8008"
  `,
  template: `
    password: "__POSTGRES_PASSWORD__"
    public_baseurl: "http://127.0.0.1:__PUBLIC_PORT__/"
    registration_shared_secret: "__REGISTRATION_SECRET__"
    macaroon_secret_key: "__MACAROON_SECRET__"
    form_secret: "__FORM_SECRET__"
  `,
  launcher: "umask 077\nopenssl rand\ndown --volumes",
  ignore: "runtime/*",
};

test("accepts pinned images and generated runtime secrets", () => {
  assert.deepEqual(inspectSynapseHarness(valid), { ok: true, errors: [] });
});

test("rejects a public homeserver binding", () => {
  const result = inspectSynapseHarness({
    ...valid,
    compose: valid.compose.replace("127.0.0.1:", "0.0.0.0:"),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /loopback/);
});

test("rejects a committed registration secret", () => {
  const result = inspectSynapseHarness({
    ...valid,
    template: valid.template.replace(
      '"__REGISTRATION_SECRET__"',
      '"0123456789abcdef0123456789abcdef"'
    ),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /registration secret/);
});
