import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  chmod,
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { inspectSynapseHarness } from "../check-synapse-integration-harness.mjs";

const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../.."
);

async function createShellHarness(t) {
  const fixtureRoot = await mkdtemp(
    path.join(tmpdir(), "synara-synapse-harness-")
  );
  t.after(() => rm(fixtureRoot, { recursive: true, force: true }));

  const scriptsDir = path.join(fixtureRoot, "scripts");
  const harnessDir = path.join(fixtureRoot, "integration", "synapse");
  const runtimeDir = path.join(harnessDir, "runtime");
  const binDir = path.join(fixtureRoot, "bin");
  await Promise.all([
    mkdir(scriptsDir, { recursive: true }),
    mkdir(runtimeDir, { recursive: true }),
    mkdir(binDir, { recursive: true }),
  ]);

  const launcher = path.join(scriptsDir, "synapse-integration.sh");
  await copyFile(
    path.join(repositoryRoot, "scripts", "synapse-integration.sh"),
    launcher
  );
  await chmod(launcher, 0o755);
  await Promise.all([
    writeFile(path.join(harnessDir, "compose.yml"), "services: {}\n"),
    writeFile(path.join(runtimeDir, ".gitkeep"), ""),
    writeFile(path.join(binDir, "docker"), "#!/bin/sh\nexit 0\n", {
      mode: 0o755,
    }),
  ]);

  const run = (command) =>
    spawnSync(launcher, [command], {
      encoding: "utf8",
      env: { ...process.env, PATH: `${binDir}:${process.env.PATH}` },
    });

  return { run, runtimeDir };
}

const valid = {
  compose: `
services:
  postgres:
    image: postgres:16.9-bookworm
    environment:
      POSTGRES_PASSWORD: \${SYNARA_POSTGRES_PASSWORD:?generated by scripts/synapse-integration.sh}
  synapse:
    image: matrixdotorg/synapse:v1.157.0
    environment:
      UID: \${SYNARA_UID:?generated by scripts/synapse-integration.sh}
      GID: \${SYNARA_GID:?generated by scripts/synapse-integration.sh}
    ports:
      - "127.0.0.1:\${SYNARA_PORT:-8008}:8008"
  `,
  template: `
    password: "__POSTGRES_PASSWORD__"
    public_baseurl: "http://127.0.0.1:__PUBLIC_PORT__/"
    registration_shared_secret: "__REGISTRATION_SECRET__"
    macaroon_secret_key: "__MACAROON_SECRET__"
    form_secret: "__FORM_SECRET__"
  `,
  launcher: `
initialize_runtime() {
  umask 077
  openssl rand
}
require_initialized_runtime() { return 0; }
clear_runtime() {
  find "$runtime_dir" -mindepth 1 -maxdepth 1 ! -name .gitkeep -exec rm -rf -- {} +
}
case "$command_name" in
  reset)
    compose down --volumes --remove-orphans
    clear_runtime
    ;;
  status)
    require_initialized_runtime
    compose ps
    ;;
  logs)
    require_initialized_runtime
    compose logs --follow synapse
    ;;
esac
`,
  ignore: "runtime/*",
};

test("accepts pinned images and generated runtime secrets", () => {
  assert.deepEqual(inspectSynapseHarness(valid), { ok: true, errors: [] });
});

test("rejects a public homeserver binding", () => {
  const result = inspectSynapseHarness({
    ...valid,
    compose: valid.compose.replace("127.0.0.1:", "0.0.0.0:"),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /loopback/);
});

test("rejects a decoy loopback string alongside a public homeserver binding", () => {
  const result = inspectSynapseHarness({
    ...valid,
    compose: valid.compose
      .replace(
        "environment:",
        'environment:\n      LOOPBACK_DECOY: "127.0.0.1:${SYNARA_PORT:-8008}:8008"'
      )
      .replace(
        '- "127.0.0.1:${SYNARA_PORT:-8008}:8008"',
        '- "0.0.0.0:${SYNARA_PORT:-8008}:8008"'
      ),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /loopback/);
});

test("rejects extra Synapse host port mappings", () => {
  const result = inspectSynapseHarness({
    ...valid,
    compose: valid.compose.replace(
      '- "127.0.0.1:${SYNARA_PORT:-8008}:8008"',
      '- "127.0.0.1:${SYNARA_PORT:-8008}:8008"\n      - "127.0.0.1:9000:9000"'
    ),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /exactly one/);
});

test("rejects published PostgreSQL ports", () => {
  const result = inspectSynapseHarness({
    ...valid,
    compose: valid.compose.replace(
      "  synapse:",
      '    ports:\n      - "127.0.0.1:5432:5432"\n  synapse:'
    ),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /PostgreSQL/);
});

test("rejects a committed registration secret", () => {
  const result = inspectSynapseHarness({
    ...valid,
    template: valid.template.replace(
      '"__REGISTRATION_SECRET__"',
      '"0123456789abcdef0123456789abcdef"'
    ),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /registration secret/);
});

test("rejects status and logs commands that initialize a clean harness", () => {
  for (const command of ["status", "logs"]) {
    const result = inspectSynapseHarness({
      ...valid,
      launcher: valid.launcher.replace(
        `${command})\n    require_initialized_runtime`,
        `${command})\n    initialize_runtime`
      ),
    });
    assert.equal(result.ok, false);
    assert.match(
      result.errors.join("\n"),
      new RegExp(`${command} must not initialize`)
    );
  }
});

test("rejects reset implementations that leave generated media and PID state", () => {
  const result = inspectSynapseHarness({
    ...valid,
    launcher: valid.launcher.replace(
      "    clear_runtime",
      '    rm -f "$env_file" "$config_file" "$signing_key_file"'
    ),
  });
  assert.equal(result.ok, false);
  assert.match(
    result.errors.join("\n"),
    /reset must clear all generated runtime state/
  );
});

test("rejects volume cleanup that appears only outside reset or in a comment", () => {
  for (const replacement of [
    "    compose down",
    "    compose down\n    # compose down --volumes --remove-orphans",
  ]) {
    const result = inspectSynapseHarness({
      ...valid,
      launcher: valid.launcher.replace(
        "    compose down --volumes --remove-orphans",
        replacement
      ),
    });
    assert.equal(result.ok, false);
    assert.match(
      result.errors.join("\n"),
      /volumes and orphans inside the reset/i
    );
  }
});

test("rejects reset cleanup that removes the tracked runtime sentinel", () => {
  const result = inspectSynapseHarness({
    ...valid,
    launcher: valid.launcher.replace(" ! -name .gitkeep", ""),
  });
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /preserving \.gitkeep/);
});

test("status and logs leave a clean runtime untouched", async (t) => {
  const { run, runtimeDir } = await createShellHarness(t);

  const status = run("status");
  assert.equal(status.status, 0, status.stderr);
  assert.match(status.stderr, /not initialized/);
  assert.deepEqual(await readdir(runtimeDir), [".gitkeep"]);

  const logs = run("logs");
  assert.equal(logs.status, 65, logs.stderr);
  assert.match(logs.stderr, /not initialized/);
  assert.deepEqual(await readdir(runtimeDir), [".gitkeep"]);
});

test("reset removes generated media, PID, config, and secret state", async (t) => {
  const { run, runtimeDir } = await createShellHarness(t);
  const mediaDir = path.join(runtimeDir, "media_store", "local_content");
  await mkdir(mediaDir, { recursive: true });
  await Promise.all([
    writeFile(path.join(runtimeDir, ".env"), "generated=true\n"),
    writeFile(path.join(runtimeDir, "homeserver.yaml"), "generated: true\n"),
    writeFile(path.join(runtimeDir, "localhost.signing.key"), "generated\n"),
    writeFile(path.join(runtimeDir, "homeserver.pid"), "1234\n"),
    writeFile(path.join(mediaDir, "object"), "generated media\n"),
  ]);

  const reset = run("reset");
  assert.equal(reset.status, 0, reset.stderr);
  assert.deepEqual(await readdir(runtimeDir), [".gitkeep"]);
  assert.equal(await readFile(path.join(runtimeDir, ".gitkeep"), "utf8"), "");
});
