#!/usr/bin/env bash
# Fail when the generated Swift API surface of SynaraCore or SynaraNseCore
# differs from the committed golden. Runs on any host: Swift sources are
# generated by the lockfile-pinned UniFFI bindgen, not by Xcode.
#
#   scripts/check-swift-api-snapshot.sh            # compare
#   scripts/check-swift-api-snapshot.sh --update   # rewrite the goldens
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
api_dir="$repo_root/synara-ios/SynaraCore/api"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

update=0
if [[ "${1:-}" == "--update" ]]; then
  update=1
fi

bindgen_target_dir="${SYNARA_APPLE_BINDGEN_TARGET_DIR:-$repo_root/target/synara-core-bindgen}"

generate() {
  local name="$1" udl="$2" out="$work_dir/$1"
  CARGO_TARGET_DIR="$bindgen_target_dir" cargo run --quiet --locked \
    --package synara-core-bindgen --manifest-path "$repo_root/Cargo.toml" \
    -- generate "$udl" --language swift --out-dir "$out" --no-format
  node "$repo_root/scripts/swift-api-surface.mjs" "$out/$name.swift" > "$work_dir/$name.swift-api.txt"
}

generate synara_core "$repo_root/crates/synara-core/src/synara_core.udl"
generate synara_nse_core "$repo_root/crates/synara-nse-core/src/synara_nse_core.udl"

status=0
for name in synara_core synara_nse_core; do
  golden="$api_dir/$name.swift-api.txt"
  if [[ "$update" == "1" ]]; then
    cp "$work_dir/$name.swift-api.txt" "$golden"
    echo "[swift-api] updated $golden"
  elif ! diff -u "$golden" "$work_dir/$name.swift-api.txt"; then
    echo "[swift-api] $name Swift API surface changed. If intended, run scripts/check-swift-api-snapshot.sh --update and review the diff." >&2
    status=1
  fi
done
if [[ "$update" == "0" && "$status" == "0" ]]; then
  echo "[swift-api] SynaraCore and SynaraNseCore Swift API surfaces match their goldens."
fi
exit "$status"
