#!/usr/bin/env bash
# Regenerate the renderer's TypeScript wire types from the Rust DTOs.
#
# Types opt in with `#[cfg_attr(feature = "ts-export", derive(ts_rs::TS), ts(export))]`.
# ts-rs writes one file per type when its generated export tests run. CI runs
# this script and fails when the committed files differ.
set -euo pipefail
export LC_ALL=C

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="$repo_root/synara/src/app/features/matrix-dto/generated"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

# u64 session generations and counters stay below 2^53 on the wire.
TS_RS_EXPORT_DIR="$work_dir" TS_RS_LARGE_INT=number \
  cargo test --quiet --locked -p synara-core --lib \
  --features ts-export,search-index,x509-identity export_bindings \
  --manifest-path "$repo_root/Cargo.toml" >/dev/null

rm -rf "$out_dir"
mkdir -p "$out_dir"
cp "$work_dir"/*.ts "$out_dir"/
{
  echo "// Generated by scripts/generate-ts-dto.sh from the Rust DTOs. Do not edit."
  for file in "$out_dir"/*.ts; do
    name="$(basename "$file" .ts)"
    [[ "$name" == "index" ]] && continue
    echo "export type { $name } from './$name';"
  done
} > "$out_dir/index.ts"
echo "[ts-dto] wrote $(find "$out_dir" -name '*.ts' ! -name index.ts | wc -l | tr -d ' ') types to ${out_dir#"$repo_root"/}"
