//! Application-domain modules shared across Synara platforms (SNC-P1-5
//! domain chunks: sync, then room_list, then timeline).
//!
//! These are pure product-domain modules moved out of the Tauri desktop shell
//! via `git mv` + path corrections; behavior is identical to the pre-move
//! src-tauri/`crate::matrix::*` surfaces, which re-export this module.

#[cfg(feature = "full-app")]
pub mod account_data;
pub mod agent_approvals;
#[cfg(feature = "full-app")]
pub mod auth;
#[cfg(feature = "full-app")]
pub mod backup;
pub mod client_builder;
#[cfg(feature = "full-app")]
pub mod cross_signing;
#[cfg(feature = "full-app")]
pub mod crypto_store;
#[cfg(feature = "full-app")]
pub mod dehydrated_devices;
#[cfg(feature = "full-app")]
pub mod devices;
pub mod diagnostics;
pub mod lifecycle;
#[cfg(feature = "full-app")]
pub mod media;
#[cfg(feature = "full-app")]
pub mod media_cache;
#[cfg(feature = "full-app")]
pub mod media_export;
#[cfg(feature = "full-app")]
pub mod members;
pub mod notifications;
#[cfg(feature = "nse-preview")]
pub mod nse_preview;
#[cfg(feature = "full-app")]
pub mod polls;
#[cfg(feature = "full-app")]
pub mod presence;
#[cfg(feature = "full-app")]
pub mod raw_content;
#[cfg(feature = "full-app")]
pub mod receipts;
#[cfg(feature = "full-app")]
pub mod relations;
#[cfg(feature = "full-app")]
pub mod room_directory;
#[cfg(feature = "full-app")]
pub mod room_keys;
#[cfg(feature = "full-app")]
pub mod room_list;
#[cfg(feature = "full-app")]
pub mod room_ops;
#[cfg(feature = "full-app")]
pub mod room_profile;
#[cfg(feature = "full-app")]
pub mod routes;
#[cfg(feature = "full-app")]
pub mod rtc_transports;
#[cfg(feature = "full-app")]
pub mod search;
#[cfg(feature = "full-app")]
pub mod secret_storage;
#[cfg(feature = "full-app")]
pub mod security;
#[cfg(feature = "full-app")]
pub mod send;
#[cfg(feature = "full-app")]
pub mod spaces;
pub mod store;
#[cfg(feature = "full-app")]
pub mod sync;
#[cfg(feature = "full-app")]
pub mod threads;
#[cfg(feature = "full-app")]
pub mod timeline;
#[cfg(feature = "full-app")]
pub mod typing;
#[cfg(feature = "full-app")]
pub mod unread;
#[cfg(feature = "full-app")]
pub mod user_profile;
#[cfg(feature = "full-app")]
pub mod user_status;
#[cfg(feature = "full-app")]
pub mod utd_recovery;
#[cfg(feature = "full-app")]
pub mod verification;
#[cfg(feature = "full-app")]
pub mod widgets;
pub mod x509;
