// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!


::uniffi::setup_scaffolding!("callback");

// Export info about this UDL file
// See `uniffi_bindgen::macro_metadata` for how this is used.

const UNIFFI_META_CONST_UDL_CALLBACK: ::uniffi::MetadataBuffer = ::uniffi::MetadataBuffer::from_code(::uniffi::metadata::codes::UDL_FILE)
    .concat_str("synara_uniffi_shape_proof")
    .concat_str("callback")
    .concat_str("callback");

#[doc(hidden)]
#[unsafe(no_mangle)]
pub static UNIFFI_META_UDL_CALLBACK: [u8; UNIFFI_META_CONST_UDL_CALLBACK.size] = UNIFFI_META_CONST_UDL_CALLBACK.into_array();







// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.


// Top level functions, corresponding to UDL `namespace` functions.

// Object definitions, corresponding to UDL `interface` definitions.


// Callback Interface definitions, corresponding to UDL `callback interface` definitions.

#[::uniffi::export_for_udl(callback_interface)]
pub trait r#Observer {
    fn r#fetch(
        &self,
    ) -> ::std::string::String;
    
}


// Export scaffolding checksums for UDL items

#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_synara_uniffi_shape_proof_checksum_method_observer_fetch() -> u16 {
    30695
}