// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!


::uniffi::setup_scaffolding!("mixed");

// Export info about this UDL file
// See `uniffi_bindgen::macro_metadata` for how this is used.

const UNIFFI_META_CONST_UDL_MIXED: ::uniffi::MetadataBuffer = ::uniffi::MetadataBuffer::from_code(::uniffi::metadata::codes::UDL_FILE)
    .concat_str("synara_uniffi_shape_proof")
    .concat_str("mixed")
    .concat_str("mixed");

#[doc(hidden)]
#[unsafe(no_mangle)]
pub static UNIFFI_META_UDL_MIXED: [u8; UNIFFI_META_CONST_UDL_MIXED.size] = UNIFFI_META_CONST_UDL_MIXED.into_array();







// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.


// Top level functions, corresponding to UDL `namespace` functions.

// Object definitions, corresponding to UDL `interface` definitions.


#[::uniffi::udl_derive(Object)]
struct r#Probe { }
#[::uniffi::export_for_udl]
impl r#Probe {
    #[uniffi::constructor]
    pub fn r#new(
    ) -> ::std::sync::Arc<r#Probe>
    {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#Probe {
    pub async fn r#fetch(
        &self,
    ) -> ::std::string::String
    {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#Probe {
    pub fn r#status(
        &self,
    ) -> ::std::string::String
    {
        unreachable!()
    }
}




// Callback Interface definitions, corresponding to UDL `callback interface` definitions.


// Export scaffolding checksums for UDL items

#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_synara_uniffi_shape_proof_checksum_method_probe_fetch() -> u16 {
    44238
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_synara_uniffi_shape_proof_checksum_method_probe_status() -> u16 {
    39525
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_synara_uniffi_shape_proof_checksum_constructor_probe_new() -> u16 {
    51628
}